### ISSUE TITLE
Splitting out gio

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/glib#117]
I'm thinking of creating a `gio` crate to avoid some workarounds and special-casing. Most of the `G*` object hierarchy (e.g. `GApplication`, `GMenu`) lives in `gio`. Generating them will be more straightforward if they have their own crate.

There's an additional wrapper complication that needs to be introduced. Turns out I've pushed convenience of declarations too far and coherence prevents cross-crate inheritance now. This can't work:
```rust
glib_wrapper! {
    pub struct Application(Object<ffi::GtkApplication>): glib::Application;
...
```
A more extended version would look like this:
```rust
glib_wrapper! {
    pub struct Application(Object<ffi::GtkApplication>): [glib::Application => gio_sys::GApplication];
```

The confusing discrepancy between `glib` and `gio` is apparent here.

**Comment by GuillaumeGomez** [comment]
If you think it's better, I'm all for it. Might be interesting to have what @EPashkin is thinking about it as well.

**Comment by EPashkin** [comment]
Separating `gio` is good idea.

**Comment by GuillaumeGomez** [comment]
I think we can close it now.
