### ISSUE TITLE
Add accessors for raw objects

### ISSUE THREAD

**Issue by Blei** [gtk-rs/glib#126]
It would be very useful to provide accessors to the raw pointers to the glib/gtk objects underlying the wrappers added by gtk-rs. This would make it easier to port applications to use parts of gtk-rs while not all needed functionality has been wrapped yet.

**Comment by GuillaumeGomez** [comment]
It is already possible (otherwise, how could do ourselves?). It's just not a good idea generally. But you have few methods ([to_glib_none](https://github.com/gtk-rs/gtk/blob/d9295b9c776c1b15ec4db0a4025838cb2f92595a/src/auto/button.rs#L42) example).

**Comment by gkoz** [comment]
To elaborate, the traits you need to work with raw pointers are in the `translate` module of this crate. All bindings rely on them and you can use them as well.

**Comment by Blei** [comment]
Looks like to_glib_none and its inverse are only available for a small selection of types. Or am I using it wrong? E.g. the following doesn't seem to work:

```rust
        let mut label = gtk::Label::new(Some(&mix.name));
        unsafe {
            let translate::Stash(l, _) = label.to_glib_none();
            gtk_label_set_line_wrap_mode(l as *mut GtkLabel, pango_sys::PangoWrapMode::Char);
        }
```

```
src/gui.rs:130:42: 130:60 error: the type of this value must be known in this context
src/gui.rs:130             gtk_label_set_line_wrap_mode(l as *mut GtkLabel, pango_sys::PangoWrapMode::Char);
                                                        ^~~~~~~~~~~~~~~~~~
```

**Comment by EPashkin** [comment]
Tried this?
```
let label = gtk::Label::new(Some(&mix.name));
unsafe {
    gtk_label_set_line_wrap_mode(label.to_glib_none().0, pango_sys::PangoWrapMode::Char);
}
```

**Comment by Blei** [comment]
That works indeed, thanks a lot!

**Comment by gkoz** [comment]
@Blei this issue was caused by the `as *mut GtkLabel` cast. The translation API works best when you let type inference choose the correct implementation. Also taking the pointer out of the stash like that is unsafe. I might just have realized there's a way to prevent that...
