### ISSUE TITLE
Add g_signal_handler_block/unblock

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/glib#133]
Needed for a project I'm working on. Should be simple to implement I think, so I'm willing to do it as I did for `signal_stop_emission*()`.

**Comment by GuillaumeGomez** [comment]
Sure, thanks if you do it!

**Comment by gkoz** [comment]
Yeah I think it should be fine (also the `disconnect` one). We use `u64` for handler id, that's what the `connect_` methods return. Will probably convert that to an opaque type later on.
