### ISSUE TITLE
GKeyFile is missing

### ISSUE THREAD

**Issue by hfiguiere** [gtk-rs/glib#135]
GKeyFile is missing from the bindings, so a bit hard to use with Rust.

Should these be auto generated or it supposed to be done by hand?

**Comment by EPashkin** [comment]
Currently glib contains no generated code, even if we add it only one function for loading files will be `load_from_file`, as others `load_from_*` can't be generated due current generator limitations:
- `load_from_file` and `load_from_data_dirs` return array
- `load_from_data` working with memory buffer.

If you want add it manually I can show generated file which can be used as template.

**Comment by hfiguiere** [comment]
I have started doing it. Lot of manual work though.

https://github.com/hfiguiere/glib/tree/keyfile

**Comment by EPashkin** [comment]
Good, I prepare generated file in 3 hour.
Minor mistakes:
- `struct KeyFile` by convention go to "key_file.rs"
- if you pass  `full_path=NULL` to `g_key_file_load_from_data_dirs`, function not return anything to it, so `from_glib_full(full_path)` just wrong

**Comment by hfiguiere** [comment]
The fullpath argument is a char** I pass "&NULL" (pointer to NULL) so it will return a newly allocated string.

**Comment by GuillaumeGomez** [comment]
&NULL is a constant pointer. Not sure this is a good idea.

**Comment by hfiguiere** [comment]
````rust
let mut full_path: *mut libc::c_char = ptr::null_mut();
````

and then I pass ````&mut full_path```` (which is ````*mut *mut i8````)

Anyway, I could test the actual binding because it seems that just adding the git repo to my crate Cargo.toml I hit an error "error: native library `gobject` is being linked to by more than one package, and can only be linked to by one package". I'll figure that one later, I'm already late.

**Comment by hfiguiere** [comment]
what should be modified is the ````*mut i8```` by being a new pointer to the string (it is ````null_ptr```` on input)

**Comment by EPashkin** [comment]
I was wrong about  `full_path`.

Also not better make `load_from_data_dirs` return type `Result<PathBuf, Error>`?

**Comment by EPashkin** [comment]
Generated code: https://gist.github.com/EPashkin/069e929501f37adbe31144fb927f6eb3

**Comment by hfiguiere** [comment]
where do we find that generator?

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/gir

**Comment by hfiguiere** [comment]
I have updated my branch with @EPashkin patches and mine.

Just "make gir" and cargo build.

**Comment by hfiguiere** [comment]
The issue here is that gir emits 
````rust 
use glib::translate::*;
````
Which is a problem.

**Comment by EPashkin** [comment]
@GuillaumeGomez, @gkoz take look please. While it good start for generating in glib, but also add combination of auto and manual parts that maybe clutter docs.

@hfiguiere, please, make PR.
IMHO need fix:
- Remove reexporting `ffi::GQuark` as better don't make it public.
- Move `error_quark` from auto to manual with changing return type to `ffi::GQueark`.
- Combine my and your first commit to one with adding `makefile` (currently it in ignored list and I missed that too).

**Comment by gkoz** [comment]
I guess we should also provide the `KEY_FILE_DESKTOP_*` constants. ([Not via reexporting](https://github.com/gtk-rs/gtk/blob/fe143389eedff019cfda70ed4ba3e2e30cac2b80/src/lib.rs#L179-L183) though because we'll eventually want to attach docs to them in this crate rather than in `glib-sys`).

**Comment by hfiguiere** [comment]
I have a patch for the KEY_FILE_DESKTOP_* in a future branch.
