### ISSUE TITLE
i18n bindings

### ISSUE THREAD

**Issue by nielsdg** [gtk-rs/glib#157]
Having bindings for the [i18n functions](https://developer.gnome.org/glib/stable/glib-I18N.html) (i.e. gettext) would be very useful.

**Comment by EPashkin** [comment]
https://crates.io/crates/gettext or https://crates.io/crates/gettext-rs won't good?

**Comment by nielsdg** [comment]
Hmm, seems I was focusing a bit too much on the printf part of it, since you can only use `format!()` with literal strings, but it seems there are crates such as [runtime-fmt](https://crates.io/crates/runtime-fmt) to fill in that void.

Of course (just a side thought) that would mean that, if an existing application would ever want to port to Rust, it couldn't reuse the translated strings (as Rust uses format strings with `"{}"` rather than `"%s"`)

**Comment by sdroege** [comment]
The `g_*gettext()`, etc. functions are bound now, and apart from that there's nothing in GLib here unless I'm missing something.
