### ISSUE TITLE
Logging functions (e.g. g_debug)

### ISSUE THREAD

**Issue by nielsdg** [gtk-rs/glib#158]
Bindings for `g_log()` and its derivatives (`g_debug()`, `g_warning()`, ...) are still missing.

One can of course use Rust's `print!()` macro's, but that means either manually parsing the G_DEBUG variable or the similar options like *--g-debug*, or ignoring them.

**Comment by sdroege** [comment]
Problem with those is that they are only macros around g_log() or g_log_structured(), which take varargs (which is also why we don't get them for free in https://github.com/gtk-rs/glib/pull/170/ ). One would have to write something around that, that works with e.g. format!() but that would mean that the final string is always created, or one would have re-implement part of the g_log() logic in Rust before calling into it (at least checking that the string is actually going to be printed based on the level, etc before creating it).

For Rust applications it's probably nicer to use the log or slog crates instead, but I can see the value of integrating with the GLib logging system.

**Comment by sdroege** [comment]
It would also make sense to have the trait from the `log` crate implemented (optionally) around the GLib logging system.

**Comment by sdroege** [comment]
Done a while ago
