### ISSUE TITLE
GMainLoop, GMainContext, GSource bindings

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#168]
Currently only the static variants around the global default main context are exposed. This is useful to have more control

**Comment by EPashkin** [comment]
All 3 can be generated.
First problem in generated `g_main_context_prepare`: `priority` don't marked as out parameter so gir use it wrong. But it can be implemented manually.
```
pub fn prepare(&self, priority: i32) -> bool {
     unsafe {
          from_glib(ffi::g_main_context_prepare(self.to_glib_none().0, priority))
      }
}
```
Also these objects many functions that need PoolFD and other currently unsupported types,
so I don't sure that generated objects will be usable and don't miss something necessary.

**Comment by sdroege** [comment]
For PollFD you can write manual code, which then exposes the underlying file descriptor. That could then be used with other Rust functions using file descriptors and potentially even things like mio.
Apart from actually finding time to write the code, there don't seem to be any problems :)

**Comment by antoyo** [comment]
These were implemented manually during the HackFest. You can see them in [futures-glib](https://github.com/antoyo/futures-glib-rs).

**Comment by sdroege** [comment]
Having non-futures versions would be useful too though (with callbacks), and then implement futures versions on top of that. I have an implementation for those somewhere from a couple of years back, have to find it :)

**Comment by antoyo** [comment]
Yeah, that would be nice.

**Comment by sdroege** [comment]
I think for the GSource API we don't necessarily want to autogenerate that but rather write it manually with the builder pattern, or a single constructor taking all relevant parts. The setter functions on GSource are not thread-safe and not supposed to be used after attachment to a main context, unlike all the other API on it.

Also need to carefully place Send and Sync bounds/impls everywhere.

**Comment by sdroege** [comment]
@antoyo did you already try switching over futures-glib?

**Comment by antoyo** [comment]
You mean using these instead of the ones in `futures-glib`?
No, I haven't done it yet.
I'm not sure I'll have everything I need, though.

**Comment by sdroege** [comment]
Shout if something is missing for you
