### ISSUE TITLE
Extending/Implementing documentation/examples?

### ISSUE THREAD

**Issue by ChaosData** [gtk-rs/glib#182]
Hi,

Is there any reference material for extending/implementing wrapped classes/interfaces using rust structs/impls?

**Comment by GuillaumeGomez** [comment]
You can "extend" them by creating your own trait and implement it on the struct, however you can't do much more.

**Comment by ChaosData** [comment]
So if a function takes a object implementing an interface, one can or cannot implement that interface in rust and pass the rust object to the function?

**Comment by GuillaumeGomez** [comment]
So, to put it simply: in Qt for example, you can extend a class by inheriting it. However, in GTK since it's C, there isn't such mechanism. Therefore, it's not really possible to do so (or at least I don't see any easy way to do it).

**Comment by EPashkin** [comment]
Check http://relm.ml/relm-intro.
There also was [article](https://siliconislandblog.wordpress.com/2016/11/22/first-rustgobject-coding-session/)  about creating custom GObject descendants

**Comment by EPashkin** [comment]
and https://people.gnome.org/~federico/news-2017-04.html#rust-gnome-hackfest-1

**Comment by EPashkin** [comment]
and http://smallcultfollowing.com/babysteps/blog/2017/05/02/gnome-class-integrating-rust-and-the-gnome-object-system/

**Comment by sdroege** [comment]
There does not seem to be anything left to be done here. Let's close this
