### ISSUE TITLE
glib::KeyFile::to_data() and glib::KeyFile::load_from_data() missing

### ISSUE THREAD

**Issue by hasufell** [gtk-rs/glib#188]
https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html#g-key-file-to-data
http://gtk-rs.org/docs/glib_sys/fn.g_key_file_to_data.html

https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html#g-key-file-load-from-data

**Comment by EPashkin** [comment]
Related to https://github.com/gtk-rs/gir/issues/388

**Comment by hasufell** [comment]
Which part exactly is problematic?

**Comment by EPashkin** [comment]
No problem if it return correct utf8 string.
As glib currently don't have build-in for [u8] conversion need be manual written.
Just need be added to https://github.com/gtk-rs/glib/blob/master/src/key_file.rs and tested.

**Comment by sdroege** [comment]
Add manual implementation for now, and once I got the other higher prio things from my TODO list I'll work on gtk-rs/gir#388 (plus the long list of little things first to actually make it work).

**Comment by sdroege** [comment]
These functions are bound since a while now
