### ISSUE TITLE
Cast/Downcast traits are unnecessarily restrictive

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#205]
Two problems here:

- Currently `upcast()` works exclusively on the `IsA<_>` trait. That is, you can only upcast from `A` to `B`, if `A: IsA<B>`. Upcasting is used (1) for going from a subclass to a parent class, or (2) for going from some class to an interface implemented by it.
Case (1) should always work fine, as it will be statically known that `A: IsA<B>` if both types are represented in Rust.
Case (2) however will fail easily: Consider a function that returns an object of type `A` according to its signature, but actually returns an object of a subclass `X` of `A` and `X` is not defined anywhere in Rust (might not even be in C headers or anywhere). This is the case for various things in GIO, and GStreamer elements.

The same also happens if you have an object of type `A`, stored in a variable of type `B` (`B` is the parent class of `A`). `A` implements interface `C` (and this is statically known) but `B` does not. You can't cast from `B` to `C` currently.

- Similarly, `downcast()` currently only works if there is a `IsA` relationship statically known between the types. Which fails in the same cases as above.

I would suggest that we deprecate/remove these traits and instead just have
- a `cast()` function that can cast between anything and checks at runtime (similar to downcast right now). This could be in `ObjectExt` also. The distinction between upcast and downcast is not really relevant here as you always have to check at runtime anyway for interfaces at least, and it can always fail.
- optionally a `static_upcast()` function (equivalent to the old `upcast()`) which only looks at the `IsA<_>` traits, and can because of that only support statically known upcasting (and never downcasting). This could be a free function, a new trait that is implemented for everything that implements `IsA<_>`, ...
- `static_downcast` (equivalent to the old `downcast`) is not really relevant or useful. It would have to check at runtime anyway, like `cast()` would, and it would only give very minor (and easily wrong, too restrictive) safety guards by the compiler.

Opinions?

**Comment by GuillaumeGomez** [comment]
I have to admit that having most of checks performed at compile-time is a great thing from my point of view. Even if in the facts we can completely break it, it's still a nice base to build upon. So except if the new system brings really huge improvements (I'm not a big user of `GIO` or `GStreamer` so I don't have your use case in mind even though I have a little idea), I think we'll need to discuss this a lot more. This isn't an easy move and I want to be sure to understand all up and down sides before deciding anything!

**Comment by EPashkin** [comment]
IMHO better don't change current functions of `trait Cast`
I don't against adding `cast` function without `IsA` bounds,
maybe with change name to `cast_dynamic` and place it to `trait Cast`, but `ObjectExt` also good place.

**Comment by sdroege** [comment]
Ok, so if you insist on keeping the existing functions they at least need a big fat warning in the docs that they are inconsistent and compilation can fail although the cast would be valid.

I agree that checking at compile-time is better than at runtime, just that with GObject interfaces this is impossible to always know at compile-time unless you know every exact type. And even then, upcasting removes the knowledge of an interface being implemented (e.g. cast a GtkVBox to a GtkWidget, and you can't cast it anymore to the GtkOrientable interface unless you first cast it to a GtkVBox again) and the cast to the interface would become impossible.

I'll send a PR for adding a `dynamic_cast` function then, and also add these warnings to the docs for the existing functions. And maybe rename the existing functions to `static_downcast` and `static_upcast`, which then have basically the same rules as the dynamic and static casts in C++?

**Comment by EPashkin** [comment]
Current functions not inconsistent but just too strict.

**Comment by sdroege** [comment]
> Current functions not inconsistent but just too strict.

Yes, they're not transitive :) Matter of opinion if that's inconsistent or only too strict

**Comment by sdroege** [comment]
I'm fine with keeping upcast/downcast as names for the current ones btw, it just seems like prefixing them with static_ would make the difference more clear. And is closer to what a C++ developer already knows.

**Comment by sdroege** [comment]
Let's close this then
