### ISSUE TITLE
Need to manually import ObjectExt

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#211]
See e.g. https://github.com/sdroege/gstreamer-rs/blob/master/examples/src/bin/gtksink.rs#L6

It is re-exported from src/lib.rs, so not sure what is missing.

**Comment by EPashkin** [comment]
Strange, it imports fine for me with both `use glib::*` and `use glib::prelude::*` on stable and nightly.
I used `.get_type()` and `.has_property("height", None)` for test

**Comment by EPashkin** [comment]
Hm. As I remember Gst also have `ObjectExt`, try switch use.

**Comment by sdroege** [comment]
It's re-exported as GstObjectExt though. But that's indeed the problem.

Niko suggested this is a compiler bug. So trying to create a test case now

**Comment by sdroege** [comment]
Maybe for the time being, I'll just not autogenerate ObjectExt and rename it directly.

**Comment by sdroege** [comment]
Same problem with ApplicationExt from GtkApplication and GApplication it seems...

**Comment by EPashkin** [comment]
Maybe we need add config `trait_name` to Gir?

**Comment by sdroege** [comment]
I guess so

**Comment by sdroege** [comment]
I'll probably get to that next week

**Comment by sdroege** [comment]
Let's consider that closed then, as part of https://github.com/gtk-rs/gir/pull/430
