### ISSUE TITLE
GSource closures are inconvenient to use in combination with GTK due to Send

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#212]
See https://github.com/gtk-rs/gtk/issues/550 with potential solution based on `SendCell` (implementation linked there).

Because `glib::idle_add()` and others require `Send` on the closure (correctly), no GTK objects (which are non-`Send`) can be used in there. GTK has a workaround by having special `gtk::idle_add()`, but adding variants for everything else that do this is not scaling.
And it does not solve the problem of actually wanting to pass a GTK object from another thread into the closure, but only use it in the closure (which is valid because it's all from the main thread).

My suggestion would be that we either get something like `SendCell` into glib, or I could also make it a separate crate and we point people with such problems to that.

SendCell code: https://github.com/sdroege/gstreamer-rs/blob/5676aeb3efaabe263f2c524746032c8441671830/examples/src/bin/gtksink.rs#L126

**Comment by sdroege** [comment]
Replying to https://github.com/gtk-rs/gtk/issues/550#issuecomment-320304158 by @EPashkin 

`From` is safe here, the only thing that can potentially panic is actually getting the value from a `SendCell` again. `From` will always work, otherwise you wouldn't have had the value to begin with.

**Comment by sdroege** [comment]
And considering https://github.com/gtk-rs/gtk/issues/550#issuecomment-320303787 , I'll add a patch for that later if @GuillaumeGomez also agrees. Or we can make it a separate crate as this might be more generally useful.

**Comment by EPashkin** [comment]
> And it does not solve the problem of actually wanting to pass a GTK object from another thread into the closure, but only use it in the closure (which is valid because it's all from the main thread).

IMHO this not issue, as there no way to create GTK object in another thread and it don't `Send`. so  existing object can't be moved to non-main thread.

**Comment by sdroege** [comment]
Yes, but with `SendCell` you could do that as long as you don't look at the value. And in C it's a very common pattern to do exactly that.

**Comment by EPashkin** [comment]
About `From`: I worried about unwanted conversion for example in call `gtk::idle_add` from non-main thread with function that capture tread linked variables,
but forgot that `From` implementation don't used automatically,
so ignore this.

**Comment by sdroege** [comment]
Exactly :) I think I'd vote for making this its own crate, it seems useful outside the scope of glib/gtk too. And we don't *necessarily* need this in glib/gtk, some applications will need it and can then depend on that crate.

**Comment by sdroege** [comment]
Did so now: https://crates.io/crates/send-cell

Do we want to re-export this from glib, or just let it be the application's worry? Is there anything we can do better for the API, like should we add variants of all the functions that ensure that it's on the current thread?

**Comment by EPashkin** [comment]
IMHO better not reexport and use crate directly when needed.
I have no idea about better API changes.

**Comment by sdroege** [comment]
Should it be mentioned in the docs? Are we mentioning other things in the docs that are required for passing state to closures (e.g. for signals) somewhere?

**Comment by GuillaumeGomez** [comment]
Docs are quite "light" for the moment. Any improvement on them is very welcome.

**Comment by sdroege** [comment]
Ok, so let's keep this open to write about things a bit in the docs.

Can you point to some examples where other "complicated" things are needed for closures, signal related?

**Comment by antoyo** [comment]
I've just had some issues with [Closure](https://github.com/gtk-rs/glib/blob/master/src/closure.rs#L34) requiring the closure to be `Send + Sync`.
And I'd like to send a `RefCell` to a `Closure`.
Is this related to this issue?

**Comment by sdroege** [comment]
Yes, you can use SendCell here if your closure is guaranteed to be called from the same thread where you created it. Otherwise you need to use a Mutex and actual data that is Send

**Comment by sdroege** [comment]
We're generally using the `fragile` crate for these things now, and there's also `SendValue` and `SendWeakRef` for making handling of such things easier.
