### ISSUE TITLE
GTypeInterfaces are not in the binding

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/glib#219]
Some places in the documentation mention interfaces, for example [this bit in the docs for IsA<>][isa-docs]

```
/// For instance, since originally `GtkWidget` is a subclass of `GObject` and
/// implements the `GtkBuildable` interface, `gtk::Widget` implements
/// `IsA<glib::Object>` and `IsA<gtk::Buildable>`.
```

I was looking at where the IsA trait is implemented for the various object types.  Let's look at the [docs for the macro][glib-wrapper-docs] that generates it...
```
/// glib_wrapper! {
///     /// A container with just one child.
///     pub struct Bin(Object<ffi::GtkBin>): Container, Widget, Buildable;
```

But in the actual [bin.rs][bin] there is only this:
```
glib_wrapper! {
    pub struct Bin(Object<ffi::GtkBin>): Container, Widget;

```

Also, GtkWidget supports Buildable and AtkImplementor ([see here][widget-ifaces]), but they are not listed in `gtk/src/auto/widget.rs`.

Some other interfaces *are* declared just fine, however.  For example, recent_chooser_widget.rs properly declares Orientable (because of Box), and the RecentChooser iface.

Also, I'm not sure how glib-rs handles calling an interface method on an instance.  For example, GTK+ has this code:
```
void
gtk_recent_chooser_set_sort_func  (GtkRecentChooser  *chooser,
				   GtkRecentSortFunc  sort_func,
				   gpointer           sort_data,
				   GDestroyNotify     data_destroy)
{
  g_return_if_fail (GTK_IS_RECENT_CHOOSER (chooser));
  
  GTK_RECENT_CHOOSER_GET_IFACE (chooser)->set_sort_func (chooser,
  							 sort_func,
  							 sort_data,
  							 data_destroy);
}
```
That `GTK_RECENT_CHOOSER_GET_IFACE()` expands to a call to `g_type_interface_peek()`, which returns NULL if the instance is not of a class that supports that interface.  I can't find any calls to `g_type_interface_peek()` in glib-rs at all :)

[isa-docs]: https://github.com/gtk-rs/glib/blob/master/src/object.rs#L111
[glib-wrapper-docs]: https://github.com/gtk-rs/glib/blob/master/src/wrapper.rs#L88
[bin]: https://github.com/gtk-rs/gtk/blob/master/src/auto/bin.rs#L14
[widget-ifaces]: https://git.gnome.org/browse/gtk+/tree/gtk/gtkwidget.c#n828

**Comment by federicomenaquintero** [comment]
Hmmm, maybe the lack of calls to `g_type_interface_peek()` is because e.g.
```
impl<O: IsA<RecentChooser> + IsA<glib::object::Object>> RecentChooserExt for O
```
implements the methods by simply calling the GTK+ functions, and *those* functions do the type checking?

**Comment by sdroege** [comment]
If the interface impl is missing, first of all check if the interface has bindings at all. In theory the interfaces would be implemented automatically by the code generator if the interface is generated and it is statically known that some class implements it.

For interface methods, it is (currently) required that there is an actual C function like the above that gets the interface and calls the vfunc.

**Comment by sdroege** [comment]
In case it wasn't clear, there are no bindings for GtkBuildable yet

**Comment by sdroege** [comment]
Should this be closed then or is there anything missing?

**Comment by federicomenaquintero** [comment]
Any ideas on why there are no bindings for GtkBuildable?  It *is* in gir-files/Gtk-3.0.gir.

Is gtk-rs/gtk/Gir.toml written by hand?  Because GtkBuildable *is* missing from there.

**Comment by GuillaumeGomez** [comment]
> Any ideas on why there are no bindings for GtkBuildable? It is in gir-files/Gtk-3.0.gir.

Either we forgot or we add an error. But this I don't have any memories bound to `Buildable`, I think we forgot. Might be worth adding it.

> Is gtk-rs/gtk/Gir.toml written by hand? Because GtkBuildable is missing from there.

It is written by hand.

**Comment by sdroege** [comment]
For the non-sys (the safe, proper bindings), you explicitly have to list all things that should go in and then make sure the output is correct and makes sense manually. That's why it's not taking everything by default.

Most things that are missing right now were just not added because nobody thought of adding them, and nobody needed them yet :) Just send PRs for everything you notice, usually it's not complicated (and ask on IRC if you need help with the tooling).

**Comment by federicomenaquintero** [comment]
Ah.  If I add `"Gtk.Buildable"` to the `generate` section of `gtk/Gir.toml`, it indeed lists the interface in the calls to `glib_wrapper!()`, and creates a `gtk/src/auto/buildable.rs`.

However, it removes the `get_name()` and `set_name()` methods from classes that have them, e.g. `gtk_file_filter_get_name()` and `gtk_widget_get_name()`.  I'm not sure how to let this interface have its own wrappers without the functions disappearing for other objects.

**Comment by GuillaumeGomez** [comment]
It's "common" to have both automatically generated code and manual code. Take a look at `*ExtManual` traits (you need to export them in prelude). Also, once you have update the `Gir.toml` file, just run `make gir` and let the magic happens. :)

**Comment by federicomenaquintero** [comment]
Thanks, @GuillaumeGomez!  That's what I needed to know.

Closing this issue; I'll file a PR for Buildable in the gtk module.
