### ISSUE TITLE
Closure::emit() / ObjectExit::emit() could use stack allocated array instead of Vec

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#223]
https://github.com/gtk-rs/glib/blob/e46aa7f27cc74f3cdcb54d94feb4a8861df21c7f/src/closure.rs#L77
https://github.com/gtk-rs/glib/blob/e46aa7f27cc74f3cdcb54d94feb4a8861df21c7f/src/object.rs#L743

It would make sense to use a stack allocated array here for < N parameters to make things more efficient and not have that many allocations per call. N = 10 for example would be sufficient already for 99% of the cases, and only uses up 10*(8+8+8) == 240 bytes of stack memory.

**Comment by EPashkin** [comment]
Agree

**Comment by federicomenaquintero** [comment]
FWIW, I got pointed the other day to https://crates.io/crates/smallvec which does exactly this :)

**Comment by sdroege** [comment]
As this is all internal for us, we can just manually write the code for that. It's adding about 4 lines to each of these functions :)
