### ISSUE TITLE
source::CallbackGuard should probably print something to stderr before exiting

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#224]
Otherwise the process just silently exits with error code 101 without anybody knowing what's going on.

**Comment by EPashkin** [comment]
Thanks for noticing this.

**Comment by sdroege** [comment]
Would be nice to put this into a bugfix release of glib, once there is something more important that requires a bugfix release

**Comment by GuillaumeGomez** [comment]
Yep. There is a small fix in `gtk` as well. I'll make a small release in a week or two.
