### ISSUE TITLE
Use ToValue trait for ObjectExt::set_property()

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#228]
https://github.com/gtk-rs/glib/blob/ba748d15e607daf4a3ef103e7e83333466d7c9eb/src/object.rs#L562-L564

Either as trait objects (which fortunately work for ToValue), or generics. Neither doesn't really make a difference, for you to decide.

Could also use ToValue for ::emit() at least, but as this is more of a plumbing function it is maybe not too useful. And for ::connect() we can't do it anyway, so maybe let's keep the symmetry there.

Comments?

**Comment by sdroege** [comment]
OTOH get_property() must return a Value, so we would lose symmetry there too. I'm fine with keeping things as is.

**Comment by EPashkin** [comment]
It is good idea.

**Comment by sdroege** [comment]
You think the asymmetry is not a problem?

**Comment by EPashkin** [comment]
Yes, it normal for rust, ex. `AsRef<Path>` vs `PathBuf` or even more common `&str` vs `String` :wink:
