### ISSUE TITLE
Use newtype wrapper around u64 for signal handler ids

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#229]
I.e. what the connect functions return. These are not arbitrary u64 but have a meaning, and we probably want to prevent people from mixing these with other u64 (or doing arithmetic on them, etc).

Might also make sense to *not* implement Copy/Clone on them (and the same for SourceId), as you can only really disconnect a signal handler once.

**Comment by EPashkin** [comment]
👍 for defining new type.
Not sure about disabling copy/clone.

**Comment by sdroege** [comment]
@GuillaumeGomez Do you have an opinion on Copy/Clone? Once that is solved I'll implement this

**Comment by GuillaumeGomez** [comment]
We should remain coherent with the rest: if it's not supposed to be in two places at once, then let's not implement Copy/Clone.

**Comment by sdroege** [comment]
You can only disconnect it once, and if you disconnect it twice you might accidentially disconnect a signal handler that was added after your first disconnect (or get a warning printed on the terminal).

Same thing for SourceId.
