### ISSUE TITLE
Wrapper has GlibType as associated type; also having the Class would be useful

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/glib#233]
I'm working on gnome-class, the code generator for gobject implementations in Rust.

If I have Gtk::Widget, I can conveniently obtain the type of the ffi struct that is wrapped (gtk_ffi::GtkWidget) by writing

```
<Gtk::Widget as glib::wrapper::Wrapper>::GlibType
```

However, I would like to be able to get to ffi:GtkWidgetClass as well.  This is so that the gobject implementation can access parent_class.finalize(), for example.

Right now we have
```
        impl $crate::wrapper::Wrapper for $name {
            type GlibType = $ffi_name;
        }
```
inside the macro `glib_object_wrapper!()`.  Could we also have a "`type GlibClassType = $ffi_class_name`" in the `Wrapper` trait?

This leads to the question of how to obtain that. I think we may need to modify `glib_wrapper!()` so that it can be called as

```
glib_wrapper! {
    pub struct Widget(Object<ffi::GtkWidget, ffi::GtkWidgetClass>): Buildable;

    match fn {
        get_type => || ffi::gtk_widget_get_type(),
    }
}
```
i.e. with an extra "argument" inside the Object<>.

This is obviously an API break.  I'm open to ideas :)

**Comment by sdroege** [comment]
I'm fine with adding another associated type to Wrapper for this. It seems to belong there, seems consistent, and the pain of fixing up code that broke because of the change should be minimal. 👍

**Comment by EPashkin** [comment]
👍 too

**Comment by GuillaumeGomez** [comment]
I don't have any problem with this and both @EPashkin and @sdroege are fine with it so it's all good!

**Comment by federicomenaquintero** [comment]
Closing now that #234 is merged.
