### ISSUE TITLE
Can't autogenerate bindings for GObject types

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#236]
... simply because library name is GLib in the Gir.toml and multiple can't be specified :) What should we do about this?

**Comment by EPashkin** [comment]
How about split glib and gobject?
Or generate gobject related binging to `src/object/auto` from separate `gobject-gir.toml`?

**Comment by sdroege** [comment]
I'd prefer the latter. In Rust you don't really ever need glib without gobject.

**Comment by sdroege** [comment]
>  Or generate gobject related binging to `src/object/auto` from separate `gobject-gir.toml`?

That's what is done now
