### ISSUE TITLE
glib::Bytes::from_static segfaults at runtime when a `&'static [u8; N]` array is passed instead of &'static u8.

### ISSUE THREAD

**Issue by alatiera** [gtk-rs/glib#242]
When passing the result of a include_bytes! macro, which is  `&'static [u8; N]`, into `Bytes::from_static(&'static u8)` it compiles fine but segfaults at runtime with error message:

`GLib:ERROR:gvariant-serialiser.c:167:g_variant_serialised_check: assertion failed (alignment & (gsize) serialised.data == 0): (5 == 0)`

When you explicitly specify `Bytes::from_static(res_bytes.as_ref())`, where as_ref makes `[u8, N]` into `u8`  it works fine.

I forked an example repo and replicated the bug [here](https://github.com/alatiera/gresource-gtkrs-example)

```sh
git clone https://github.com/alatiera/gresource-gtkrs-example.git
cd gresource-gtkrs-example
cargo run
```

Crate versions I used:
gio = "0.2"
glib "0.2"

**Comment by sdroege** [comment]
The variant that you say works for you also fails the same way here for me. What works is all variants that copy the data instead of statically referencing it.

**Comment by sdroege** [comment]
The problem is that for some reason the content of the GBytes is different at a later time once the GResources are actually used by the GtkBuilder, but only if the array is statically referenced instead of copied into the GBytes.

It is as if the array is only valid inside the scope of that function, but as it's a &'static this shouldn't be the case.

**Comment by alatiera** [comment]
That's weird, I re-cloned repo and tryed a clean build && run and it was still working, I even tried after a cold boot to ensure that there wasnt anything in ram and it was still working.

Even weirder I can't reproduce the success on another project even if I copy paste it exactly.

All of the above on nightly. I just tried running the forked repo on stable and Indeed fails with both ways, so that might be a regression in nightly then?

**Comment by sdroege** [comment]
We're running into a memory safety bug here, if it crashes or not depends on the context, compiler, optimizations, etc.

It's as broken in stable as in nightly. I'll look closer later and try to simplify the testcase. This does not need GResource for example

**Comment by sdroege** [comment]
The problem here is AFAIU that GVariant or GVdb requires that the memory passed has a proper alignment. It has to be at least pointer-aligned. But that's not the case here with byte arrays, they don't have to.

**Comment by sdroege** [comment]
Will file a bug against GLib with a small testcase, this is just broken there :)

**Comment by sdroege** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=790030

**Comment by sdroege** [comment]
For now the workaround is to *always* use `Bytes::from` and never `Bytes::from_static` here. It means another memcpy, but it will always work.

**Comment by sdroege** [comment]
It might make sense for now to add a check to Resource::new_from_data() whether the GBytes is correctly aligned, and if not to simply copy it internally.
