### ISSUE TITLE
IsA<> trait has to be unsafe

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#246]
As @alexcrichton noticed yesterday, the `IsA<>` trait must be unsafe. Otherwise you could safely implement it e.g. `impl IsA<gtk::Button> for gtk::Label` or similarly silly things.

Making the `ToGlibPtr` trait unsafe would also solve that, but that one generally seems fine. You can safely convert a `gtk::Button` to a `*mut gtk_ffi::GtkButton`, you just can't dereference that pointer safely (but you never could do that anyway).

**Comment by sdroege** [comment]
@GuillaumeGomez @EPashkin Any opinions?

**Comment by EPashkin** [comment]
Unsafe `IsA<>` seems reasonable.

**Comment by GuillaumeGomez** [comment]
It seems a bit weird for me since the `IsA` trait is implemented only from the `gtk-rs` crates. But apart from this, I don't have any objection.

**Comment by sdroege** [comment]
ToGlibPtr and ToGlibPtrMut have the same problem, they could be used for changing types in incompatible ways by doing a bad, safe impl.

So should also be unsafe. FromGlibPtr should be fine as its functions are all unsafe already

**Comment by sdroege** [comment]
This should be handled before the next release

**Comment by sdroege** [comment]
Actual ToGlibPtr* is fine, you can already safely cast between arbitrary pointer types.
