### ISSUE TITLE
glib::Error's Debug impl is useless

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#247]
It currently prints the pointer to the GError, but not the actual content of the error. While generally this is fine, for everything implementing std::error::Error this is suboptimal: when observing an error, the standard way of printing it is via the Debug trait (and not Display).

**Comment by sdroege** [comment]
I would propose adding another parameter to the wrapper macro, which if not given defaults to the current behaviour. And it would be a list of traits to implement, e.g. `[PartialEq, Eq, Debug]`

Sounds good?

**Comment by GuillaumeGomez** [comment]
If it's optional then sure!

**Comment by sdroege** [comment]
That would also allow us to disable the `Eq` impl we currently add for some types (eq by pointer) where there is a more useful comparison function possible.

Ok, I'll go for that then :)

**Comment by GuillaumeGomez** [comment]
👍
