### ISSUE TITLE
GValue can be used to violate Send/Sync traits

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#253]
E.g. you can store a gtk::Widget in a GValue and then send it to another thread. GValue is (and should be) Send, but it's content might not be.

A solution might be to have two kinds of Value, one Send and one not. And being able to transform from the Send one to the other, similar to TypedValue.

**Comment by sdroege** [comment]
SendValue seems most reasonable, but not sure how to do this most painless. Code generator needs support for this too, so that Send type functions only allow SendValue.

**Comment by EPashkin** [comment]
Agree.

**Comment by sdroege** [comment]
Let's also get this one fixed before the release then :) known safety issues are not fun

**Comment by sdroege** [comment]
Working on it btw, not very focussed right now but adding a trait impl at a time to make things work without problems
