### ISSUE TITLE
DerefMut on TypedValue is unsafe

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#254]
```rust
let mut meh: TypedValue<i32> = (&123i32).into();
let meh2: Value = (&1u8).to_value();
*meh = meh2;
```

And suddenly we have a `TypedValue<i32>` that actually contains an `u8`.

**Comment by sdroege** [comment]
Is `DerefMut` ever actually needed or can we just remove it? @GuillaumeGomez @EPashkin ? :)

**Comment by GuillaumeGomez** [comment]
Oh damn. That's quite terrible! 😱 

And no idea about `DerefMut`...

**Comment by sdroege** [comment]
I don't think `DerefMut` is of any use here, other than overwriting the value with a different one of potentially a different type. I wouldn't know how to use it otherwise at least.

**Comment by EPashkin** [comment]
Agree that current version is unsafe.
Just removing it will broke `impl<'a, T: FromValueOptional<'a> + SetValue> TypedValue<T> {`,
so maybe it can be replaced with internal alternative.

**Comment by sdroege** [comment]
Sure, that can easily be rewritten. I meant I see no usage *outside* value.rs :)
