### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by daa84** [gtk-rs/glib#267]
Can't say exactly, but think it is error. For me this introduce memory leak.
Here call to container function
https://github.com/gtk-rs/glib/blob/d9961b3f0eafb15c84d390f28cf8a502a632d419/src/translate.rs#L1257

but functin is from_glib_full_as_vec, so as i understand it must also transfer owning of items. so it must be from_glib_full_num ?

**Comment by EPashkin** [comment]
@daa84 On what function?

**Comment by EPashkin** [comment]
cc @sdroege as author of https://github.com/gtk-rs/glib/pull/198

**Comment by EPashkin** [comment]
Actually use `from_glib_container_num` in full conversion was added long ago in https://github.com/gtk-rs/glib/pull/27 or even sooner.

**Comment by daa84** [comment]
I don't understand why both functions:
```rust
    unsafe fn from_glib_container_as_vec(ptr: *mut glib_ffi::GSList) -> Vec<T> {
        let num = glib_ffi::g_slist_length(ptr) as usize;
        FromGlibContainer::from_glib_container_num(ptr, num)
    }

    unsafe fn from_glib_full_as_vec(ptr: *mut glib_ffi::GSList) -> Vec<T> {
        let num = glib_ffi::g_slist_length(ptr) as usize;
        FromGlibContainer::from_glib_container_num(ptr, num)
}
```
calls FromGlibContainer::from_glib_container_num ?

**Comment by EPashkin** [comment]
@daa84 I understand that, it really strange. I asking what function you calling, and it produce memory leak?

**Comment by daa84** [comment]
Ah, ok, i use direct call inside my code, pango_itemize, that returns list of items that also must be freed. As this function not implemented in gtk-rs i just call it directly but convert result with from_glib_full

**Comment by sdroege** [comment]
Yes, that should also call `from_glib_full_num`. Do you want to send a PR?

**Comment by daa84** [comment]
Yes, but i do it later :smile:

**Comment by sdroege** [comment]
@daa84 Do you need some help?

**Comment by daa84** [comment]
@sdroege Sorry, i have no time today. Can you fix it?
Note that there is at least two places where this must be fixed. Maybe more i don't check it all.

**Comment by sdroege** [comment]
Sure, checking :)

**Comment by sdroege** [comment]
All other places except for GList/GSList look correct

**Comment by daa84** [comment]
Thanks
