### ISSUE TITLE
markup_escape_text

### ISSUE THREAD

**Issue by jD91mZM2** [gtk-rs/glib#280]
Hi! I can't find a `markup_escape_text` function. In your Gir.toml it says "ignored = true", so I guess it's disabled. Is there any alternative, or any plans to enable it?

**Comment by sdroege** [comment]
This should be handled fine now with all the gir changes in the past, just not ignoring it should be enough.

**Comment by sanpii** [comment]
Have you planned a release soon with this feature?

**Comment by GuillaumeGomez** [comment]
Soon I don't know. Some day for sure.

**Comment by sanpii** [comment]
@GuillaumeGomez this is because I have a bug that requires this function. I don’t know if I wait a release or rewrite a similar function :thinking:

**Comment by GuillaumeGomez** [comment]
You can just use the github version directly.
