### ISSUE TITLE
Exclude gir-files directory in Cargo.toml

### ISSUE THREAD

**Issue by RazrFalcon** [gtk-rs/glib#289]
The current `glib-0.4.1.crate` package contains this folder, which is 20MiB big and the `.crate` file itself is 2MiB.

AFAIU, this directory is not needed during compilation, so it can be safely excluded, which will reduce the file size.

**Comment by EPashkin** [comment]
Then `gir` folder need be excluded too.

**Comment by RazrFalcon** [comment]
It isn't present in the `.crate`.

**Comment by EPashkin** [comment]
Good to hear, I don't know how get `.crate`, so just looked to `$USER_HOME$\.cargo\git\checkouts\glib-928cf7b282977403`

**Comment by RazrFalcon** [comment]
It can be found in `.cargo/registry/cache/github.com-*/` or `target/package/`

**Comment by EPashkin** [comment]
Thanks

**Comment by EPashkin** [comment]
Only 2 last unmerged

**Comment by GuillaumeGomez** [comment]
Done as well.

**Comment by EPashkin** [comment]
All crates in gtk-rs processed.
Sys'es and some other unaffected by this bug.

**Comment by MathieuDuponchelle** [comment]
This has an annoying side effect: I want to try and generate automatic bindings for TlsDatabase, but I'd like to make sure I generate them from the same gir file that was used, how can I tell now ? :)

**Comment by MathieuDuponchelle** [comment]
Hm don't mind me, they're all in gtk-rs/gtk :)

**Comment by sdroege** [comment]
So let's close this? :)
