### ISSUE TITLE
Debug info for panic in FFI

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/glib#304]
Hi.
I had a lot of trouble to debug [this issue](https://github.com/gtk-rs/gio/issues/99), so instead of just having "Uncaught panic, exiting", it would be nice to have more info maybe the stack trace, to be able to debug.
Thanks.

**Comment by EPashkin** [comment]
This not under gir control, see https://github.com/gtk-rs/glib/blob/master/src/source.rs#L75-L85

**Comment by antoyo** [comment]
I know this message comes from this code, but perhaps `gir` could generate code using `catch_unwind()` or something.
Or perhaps in the code you mentioned we should get the stack trace in the condition using libbacktrace.

**Comment by EPashkin** [comment]
Need of `CallbackGuard` will be removed in 1-2 rust stable release,
as rust will be do it yourself, then I hope `RUST_BACKTRACE` will works as usual.
See end of https://github.com/gtk-rs/glib/pull/250.

**Comment by EPashkin** [comment]
@antoyo As you have panic test case, can you check that panic will be caught without this line https://github.com/gtk-rs/gio/blob/master/src/auto/socket_listener.rs#L99 and that `RUST_BACKTRACE=1` works as usual ?

**Comment by EPashkin** [comment]
I mean that unwinding already landed in last stable (second time), we just waiting to be sure that it will be not reverted again.

**Comment by antoyo** [comment]
Yeah, I see the backtrace on Rust nightly.

**Comment by EPashkin** [comment]
Thanks for confirming, so we just wait for stable 1.26.0 and remove `CallbackGuard` again

**Comment by sdroege** [comment]
> I mean that unwinding already landed in last stable (second time)

It was not ready for 1.25 unfortunately

**Comment by EPashkin** [comment]
Then we better wait for stable 1.27.0
