### ISSUE TITLE
Object set_property doesn't work with interfaces / derived types.

### ISSUE THREAD

**Issue by tmiasko** [gtk-rs/glib#307]
Object set_property currently validates that value has exactly the same type as
property, which means you can't use it with derived types / types that
implement given interface.

**Comment by sdroege** [comment]
Indeed, want to send a PR? Probably the same issue with the GValue getter/setter for objects

**Comment by sdroege** [comment]
You could use `Type::is_a` here. Transform is not ideal as there are transform functions from/to strings, for example. IMHO all this should only consider subtyping

The checks could be removed but I'd prefer a proper error on the Rust side over an "unobservable" critical in GLib

**Comment by tmiasko** [comment]
But my point is, that `g_object_set_property()` already uses those transforms, and we are just making this invalid.

**Comment by sdroege** [comment]
So you can pass `1` to a boolean property and it becomes `TRUE`? Basically any fundamental type could be set on a string property. And even from integers to enums/flags. I did not know that but according to `gobject.c` you're right. How ugly :)

So a correct check would be `g_value_type_transformable()` and  `g_param_value_validate()` (which unfortunately already needs the transformed value... plus the flags check). But we might want to be more restrictive here, e.g. passing arbitrary integers to enum/flags properties kind of defeats the purpose of our nice enum/flags types.

My feeling would be, like I said above, that we should allow subtyping but no other kinds of type mismatches. For the same reason we use proper enums/flags, and Rust does not automatically cast between different integer types, etc.. We might want to move `g_param_value_validate()` into the Rust wrapper though to also do range checking.

And as I mentioned above, I assume the same problem with regards to subtyping exists in the GValue getter/setter impls.

**Comment by sdroege** [comment]
The GValue setters/getters already take subtyping into account, and only that (no transforms)

**Comment by tmiasko** [comment]
This was fixed in #311.
