### ISSUE TITLE
Rename MainContext::ref_thread_default() to ::get_thread_default() and remove the other one

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#332]
The behaviour of `get_thread_default` to return `None` for the default main context is not very intuitive or useful, and that's the only difference in behaviour on the Rust bindings side.

I would replace it with `ref_thread_default`.

CC @GuillaumeGomez @tmiasko @EPashkin @russel

**Comment by EPashkin** [comment]
Currently `ref_thread_default` return Option too, but agree that it return None only if constructor fail.
So 👍

**Comment by sdroege** [comment]
`ref_thread_default` never returns `None` iirc (unless all is broken), will check the C code if people agree that this is the way forward though

**Comment by EPashkin** [comment]
Problems:
Documentation will be wrong after rename,
Not sure if this real case, but it possible for someone need to know has current thread specific MainContext or not.

**Comment by tmiasko** [comment]
After looking at C code, making g_main_context_ref_thread_default non-nullable looks fine.
But I would be wary of renaming it. I find it beneficial that one can switch to another 
language and get the same semantics from bindings. Renaming will only add to the confusion
for people who already know GLib or look at documentation for C.

**Comment by sdroege** [comment]
Then let's go with that :)

**Comment by sdroege** [comment]
Thanks for your input
