### ISSUE TITLE
Restructuring

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/glib#337]
@GuillaumeGomez, @sdroege, @antoyo, @tmiasko 

First, sometimes we want to generate types from gobject (like "Binding" in https://github.com/gtk-rs/glib/pull/322),
Secondly, we have 2 big files: translate.rs (1734 lines) and object.rs (1054 lines)
Therefore, I propose change module structure with separate glib/gobject modules and split translate/object.
Result will look something like this:
```
.
├── Gir.toml
├── Gir_object.toml
├── src
│   ├── boxed.rs
│   ├── glib
│   │   ├── auto
│   │   │   ├── enums.rs
│   │   │   ├── flags.rs
│   │   │   ├── functions.rs
│   │   │   ├── main_context.rs
│   │   │   └── mod.rs
│   │   ├── bytes.rs
│   │   ├── char.rs
│   │   ├── checksum.rs
│   │   ├── date.rs
│   │   ├── date_time.rs
│   │   ├── enums.rs
│   │   ├── functions.rs (currently named utils.rs)
│   │   ├── main_context.rs
│   │   ├── main_context_futures.rs
│   │   ├── mod.rs
│   │   ├── string.rs
│   │   ├── time_val.rs
│   │   ├── variant.rs
│   │   └── variant_type.rs
│   ├── gobject
│   │   ├── auto
│   │   │   └── mod.rs
│   │   ├── closure.rs
│   │   ├── mod.rs
│   │   ├── types.rs
│   │   └── value.rs
│   ├── object
│   │   ├── mod.rs
│   │   └── weakref.rs
│   ├── prelude.rs
│   ├── shared.rs
│   ├── signal.rs
│   ├── source.rs
│   ├── source_futures.rs
│   ├── translate
│   │   ├── array.rs
│   │   ├── carray.rs
│   │   ├── hashtable.rs
│   │   ├── list.rs
│   │   ├── mod.rs
│   │   ├── osstring.rs
│   │   └── path.rs
│   └── wrapper.rs
└── versions.txt
```

Also see https://github.com/gtk-rs/glib/issues/236

**Comment by sdroege** [comment]
Great idea, i believe @guillaumegomez also planned something like this. Only one question: what's the difference between object and gobject? Object is the GObject type and gobject the library? I would move the type to gobject/object.rs

Otherwise seems all fine

**Comment by EPashkin** [comment]
Yes, object module is current object.rs that contains some submodules (Ex. WeakRef).
Agree that it can moved into gobject with weak_ref on same level.
Then IMHO we can have `object.rs` with only macro `glib_object_wrapper`.

**Comment by GuillaumeGomez** [comment]
Ah perfect! I wanted to finish #336 before starting this but if you are doing it, even better! :)

**Comment by EPashkin** [comment]
I will wait for #336 too anyway 😉

**Comment by sdroege** [comment]
Related to this, I'm trying to autogenerate some code from GObject. However we have to use a different toml file for that (the main one is for GLib), and somehow need to store the results in a different location. And gir also has to believe it is in the glib crate to generate proper use statements. Suboptimal!

Can we solve that as part of the reorganization?

**Comment by GuillaumeGomez** [comment]
Do you have an idea on how to solve this issue by any chance?

**Comment by EPashkin** [comment]
I thought that already change gir to support custom target location, but seem it still not done.

> And gir also has to believe it is in the glib crate to generate proper use statements. Suboptimal!
Yes it can be problem.

By way which object you tried to generate? When I find in gobject only Binding, other was unusable for me.

**Comment by sdroege** [comment]
> By way which object you tried to generate? When I find in gobject only Binding, other was unusable for me.

https://github.com/gtk-rs/glib/pull/349, see also last comment there :)

The ParamSpecs would be another thing to generate. But maybe we can just ignore that, there are not many types in GObject.

**Comment by EPashkin** [comment]
How about add parameter "options.auto_path" (defaults = "auto"),
that replaced "auto" in https://github.com/gtk-rs/gir/blob/master/src/codegen/mod.rs#L47 ?

**Comment by EPashkin** [comment]
or default to "src/auto" to replace addition completely

**Comment by sdroege** [comment]
Agreed to all that, yes

**Comment by EPashkin** [comment]
Then I start work on this.

**Comment by sdroege** [comment]
Let's close this then? PR was merged long ago
