### ISSUE TITLE
Move `ErrorDomain` trait to safe `GQuark` bindings

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#363]
See summary. Now that we have `GQuark` bindings we should also make use of them :)

@GuillaumeGomez Something for you?

**Comment by GuillaumeGomez** [comment]
You can do it too if you want. lot of work on rustdoc. ;)

**Comment by EPashkin** [comment]
@sdroege You meant something like this?
```rust
pub trait ErrorDomain: Copy {
    /// Returns the quark identifying the error domain.
    ///
    /// As returned from `g_some_error_quark`.
    fn domain() -> Quark;
```
```rust
impl ErrorDomain for FileError {
    fn domain() -> glib_ffi::GQuark {
        unsafe { from_glib(glib_ffi::g_file_error_quark()) }
    }
```
Then it IMHO work for me as git need change too.

**Comment by sdroege** [comment]
Yes, exactly that.

**Comment by EPashkin** [comment]
@GuillaumeGomez All 4 PR linked to issue IMHO ready for merge

**Comment by GuillaumeGomez** [comment]
I assume it's normal they're all failing?

**Comment by EPashkin** [comment]
Yes, only gtk that I will add latter must pass CI before merge

**Comment by GuillaumeGomez** [comment]
Done!

**Comment by sdroege** [comment]
Let's close this one then, all but gtk done :)
