### ISSUE TITLE
Reduce duplication of property name when subclassing

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#407]
See https://github.com/gtk-rs/glib/blob/0e3c1cbca20e84288124f0a6d4a2f1d3cca0b625/src/subclass/object.rs#L305-L312

Currently the "name" has to be provided twice. Once as a marker for the property so we can directly match on it in the property getter/setter, and once for creating the pspec. This is not very beautiful :)

Does someone have any ideas how to make this nicer?

One idea I would have is to change this to
```rust
        Property("name", |name| {
            ::ParamSpec::string(
                name,
                "Name",
                "Name of this object",
                None,
                ::ParamFlags::READWRITE,
            )
}),
```
I.e. letting the caller pass in the property name taken from `property.0`.

CC @fengalin

**Comment by sdroege** [comment]
Any other suggestions? Then I would implement that

**Comment by EPashkin** [comment]
IMHO it good way to do
