### ISSUE TITLE
Add subclassing API for adding/implementing interfaces

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#408]
The discussion started here: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/issues/165

It also contains a proposal that I'll shortly copy here

Registration of the type directly on InitializingType (note to self: we should also get rid of the Deref<Target=Type> impl on InitializingType):

```rust
impl<T: ObjectSubclass> InitializingType<T> {
    pub fn add_interface<I: IsInterface>(&mut self)
        where T: IsInterace::ImplType {
        unsafe {
            let iface_info = gobject_ffi::GInterfaceInfo {
                interface_init: Some(I::interface_init::<T>),
                interface_finalize: None,
                interface_data: ptr::null_mut(),
            };
            gobject_ffi::g_type_add_interface_static(
                self.0.to_glib(),
                I::static_type(),
                &iface_info,
            );
        }
    }
}
```

A new trait for interfaces

```rust
pub trait IsInterface {
    type ImplType;
    unsafe extern "C" fn interface_init<T: ObjectSubclass>(iface: glib_ffi::gpointer, _iface_data: glib_ffi::gpointer)
        where T: Self::ImplType;
}
```

Usage in the type_init() function would then be:

```rust
    type_.add_interface::<gst::URIHandler>();
```

**Comment by sdroege** [comment]
CC @fengalin

**Comment by fengalin** [comment]
@sdroege thank you for declaring the issue. I'll work on it this weekend.

**Comment by fengalin** [comment]
@sdroege, I've been fighting the type system (with no success) trying to implement your proposal for constraining the `Interface`'s `ImplType`. I run into multiple issues which I am unable to solve.

Here is a [working playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=951408e1cebeb9293462c38d3ca0ee74) with what I believe is the bare minimum to simulate the overall architecture for this particular matter. I commented the pieces for the type constraints where I think they fit and the matching error they generate.

I'll keep trying, but if you see any obvious mistake, that would help me tremendously!

**Comment by sdroege** [comment]
Ah I see the problem... we need `ImplType` to be not a specific type but a trait. Basically an "associated trait" instead of "associated type". I don't think GATs can do that either.

Back to square one and let's think about it a bit more :)

Basically what we somehow need is to enforce that the `T` passed in there implements a specific trait, a trait that is specific and different for each `IsInterface` / `IsImplementable` (whatever) impl. And we don't want to go through a trait object (which is what your implementation would do, just that `URIHandlerImpl` is not object-safe so it fails).

**Comment by sdroege** [comment]
Ah I found a solution probably. Let me try that :)

**Comment by sdroege** [comment]
@fengalin see https://github.com/gtk-rs/glib/pull/415

The trick was to give the `IsImplementable` interface a type parameter that must implement the `ObjectSubclass` trait. And then have a blanket implementation `impl<T: ObjectSubclass + URIHandlerImpl> for URIHandler {}` to enforce that whatever we call this one actually implements the trait we care about.

**Comment by fengalin** [comment]
@sdroege: of course, and it even looks simpler!

I'm just not too fond of the "**Is**" prefix though. :)
