### ISSUE TITLE
Update minimum supported version to 2.42

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#436]
We currently have 2.32 as minimum supported version. Nobody is going to test the bindings with such old versions and it makes some very useful API hidden behind feature flags :)

2.42+ is in Debian *old*stable, Ubuntu 16.04 and more than 4 years old. Similarly we should update the minimum version of the other crates too to the equivalent version of the library that was released together with GLib 2.42.

We might also want to make sure that deprecated API that was removed before that minimum version is completely removed from the bindings.
Overall that should cause quite some cleanup in any case.

Opinions? :)

**Comment by sdroege** [comment]
CC @GuillaumeGomez @EPashkin

**Comment by EPashkin** [comment]
This version equals of gtk3.0 IMHO we need increase version at the same time

**Comment by sdroege** [comment]
For GTK that would be 3.14. For each library we need to check the release that happened around September 2014 (GNOME 3.14).

**Comment by sdroege** [comment]
The main question here is whether this is "too new" for some use-case we want to support. I'm not aware of anything, and it's older than Rust 1.0 still.

**Comment by GuillaumeGomez** [comment]
Is it a problem to support older versions or not? Here's the only question that really matters. :)

**Comment by sdroege** [comment]
> Is it a problem to support older versions or not? Here's the only question that really matters. :)

Nobody tests with such old versions, and what is not tested is by definition broken.

Apart from that, having such old version "supported" means having lots of API disabled by default, API that would be useful to have. And it means having a lot of `#[cfg(...)]` everywhere in the code, that are easy to get wrong. It's a maintainance burden.

**Comment by GuillaumeGomez** [comment]
If we have to maintain them by hand, yes it is. Considering we're talking about glib in here, I assume it's a common case. Then how should we pick the "old enough" version?

**Comment by sdroege** [comment]
> If we have to maintain them by hand, yes it is. Considering we're talking about glib in here, I assume it's a common case. Then how should we pick the "old enough" version?

In GStreamer we usually do that by looking at what's in the LTS/stable Linux distros. That's why I mentioned Debian oldstable and the Ubuntu LTS before the current LTS above.

**Comment by sdroege** [comment]
That said, my main worry here is really the API being hidden and not very discoverable... and a lot of deprecated API still exposed that would better not be there. It's not very user-friendly.

**Comment by sdroege** [comment]
Let's see if some concern comes up until after FOSDEM and then I would send some PRs doing exactly that :)

**Comment by sdroege** [comment]
@EPashkin @GuillaumeGomez any new opinions? :)

**Comment by EPashkin** [comment]
I don't use old version, so 👍

**Comment by EPashkin** [comment]
but better not gone up too high, IMHO almost all stable linux better covered

**Comment by sdroege** [comment]
Yeah, September 2014 / GNOME 3.14 would be the version I'd use. That'd still be many versions older than all the enterprise/LTS distros out there currently have.

**Comment by EPashkin** [comment]
@sdroege As I understand glib2.42 is used in Debian jessie (oldstable) with gtk3.14.
So we change other packages version to jessie's?
Note:
Oldest Ubuntu trusty (14.04LTS)  has libgtk-3-0 (3.10.8-0ubuntu1.4) + libglib2.0-0 (>= 2.39.4) 
Previous Ubuntu Xenial (16.04LTS)  has libgtk-3-0 (= 3.18.9-1ubuntu3)  + libglib2.0-0 (>= 2.45.8)

**Comment by sdroege** [comment]
I would change all versions to what came out with GNOME 3.14. That should be the same as what is in Debian jessie.

I wouldn't worry about Ubuntu trusty at this point, it's already *three* LTS releases in the past.

**Comment by GuillaumeGomez** [comment]
I don't really have an opinion in here. I'll just follow the global opinion. :)

**Comment by EPashkin** [comment]
Ok, lets do it.

**Comment by sdroege** [comment]
This can be closed then :)
