### ISSUE TITLE
Allow use buildin accumulators

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/glib#439]
`glib::subclass::types::add_signal_with_accumulator` and orher `add_signal_with_accumulator`s allow use accumulator closure in rust.
This add unneeded C-to-Rust call and can avoided by adding trait `SignalAccumulator` that allow
get all needed parameters for C (inital value, function).
Glib can implement enum and trait for it
```
enum SignalAccumulator {
  None, //Without accumulator
  TrueHandled, //g_signal_accumulator_true_handled
  FirstWin, //g_signal_accumulator_first_wins
  Custom(Fn(...)) // Instead this trait can implemented on Fn directly
}
```
Other crates can define enums to Ex. gio has `g_application_handle_local_options_accumulator`.
Note, as @sdroege mentioned latest can be just rust function but this allow remove unneeded boundary cross
```
|return_acc, handler_return| {
  let value = handler_return.get::<u32>().unwrap();
  *return_acc = value.to_value();
  value < 0
}
```

**Comment by sdroege** [comment]
An enum like this has the same problem as what we had with `Option<Fn()>` a few days ago. Let's not go that route :)



>  TrueHandled, //g_signal_accumulator_true_handled

```rust
|acc, res| {
  let val = res.get::<bool>().unwrap();
  *acc = res;
  !val
}
```

>  FirstWin, //g_signal_accumulator_first_wins

```rust
|acc, res| {
  *acc = res;
  false
}
```

I'm not sure it's worth complicating the API for being able to use those trivial accumulators directly, and the overhead of putting a Rust closure around those functions is something we can ignore IMHO. And if we have bindings for the accumulators from GLib/etc we can also directly pass those without putting a closure around it.

The main problem right now is that we're not passing the signal invocation hint to the accumulator callback. That could relatively easily be added.

The way how the signal invocation hint works we'll have to write bindings for the accumulators from glib/etc manually.

**Comment by EPashkin** [comment]
After some thinking, I agree with you, even in my proposal we need go C-to-Rust on each call anyway.
