### ISSUE TITLE
MainContext::channel fails to attach to default main context

### ISSUE THREAD

**Issue by gdesmott** [gtk-rs/glib#448]
According to the doc passing `None` as context to `attach()` should attach it to the default context but I get the panic: `assertion failed: context.is_owner()`.

```rust
pub fn main() {
    let (tx, rx) = glib::MainContext::channel(glib::PRIORITY_DEFAULT);
    let l = glib::MainLoop::new(None, false);

    rx.attach(None, move |u| {
        dbg!(u);
        glib::Continue(true)
    });

    tx.send(10).unwrap();
    l.run();
}
```

CC @sdroege

**Comment by sdroege** [comment]
You first have to own the main context before you can do that. `glib::MainContext::default().acquire()` for example, or do it from inside of a `GApplication` callback or anything else called from the main context.

`gtk::init()` will acquire the default main context by itself soon. https://github.com/gtk-rs/gtk/pull/780

**Comment by gdesmott** [comment]
Indeed, I was assuming this was done automatically. Thanks!
