### ISSUE TITLE
Add get/set_property methods to ObjectExt

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/glib#45]
https://developer.gnome.org/gobject/stable/gobject-The-Base-Object-Type.html#g-object-get-property

There is an empty [ObjectExt trait](https://github.com/rust-gnome/glib/blob/master/src/object.rs#L218-222) that should receive the appropriate methods.

**Comment by gkoz** [comment]
This seems complicated by this `get_property` requirement
> `value` must have been initialized to the expected type of the property (or a type to which the expected type can be transformed) using `g_value_init()`.

It's not yet clear how to implement type checking in these circumstances.

**Comment by gsingh93** [comment]
Well we'd have to get the type of passed in value, get the type of the property (with `g_object_class_find_property`), and then just compare the two, right?

**Comment by gkoz** [comment]
An object's properties are known in advance aren't they? We could declare them similarly to signals, providing static type checking.

**Comment by gsingh93** [comment]
Sure, it just seems like a lot of work, but that does seem like the right approach.

**Comment by Susurrus** [comment]
Just tried to use this today and found this issue. Is anyone working on this or what's required to push this forward?

**Comment by EPashkin** [comment]
IMHO this was abandoned due unsafety. Currently we have new https://github.com/gtk-rs/gir/issues/304 and I plan work on it.
@Susurrus, you can wait until fix landed or add needed getter\setters to your project using child properties (https://github.com/gtk-rs/gtk/pull/416) as example

**Comment by EPashkin** [comment]
@GuillaumeGomez, IMHO this can be closed now.

**Comment by GuillaumeGomez** [comment]
Indeed!
