### ISSUE TITLE
Crates.io has a version of glib that isn't in the repository?

### ISSUE THREAD

**Issue by kornelski** [gtk-rs/glib#452]
0.6.1 has been published: https://crates.io/crates/glib/0.6.1

but this repo currently contains 0.6.0: https://github.com/gtk-rs/glib/blob/master/Cargo.toml#L8

**Comment by sdroege** [comment]
Yeah that's because of how the release script works unfortunately.

@GuillaumeGomez can you make sure that the release script for the next release immediately updates the version in master to the next one (i.e. the next release is 0.7.0, so the version in git master right after the release should become 0.8.0)? It's only causing problems otherwise :) You might remember that I mentioned this before

**Comment by GuillaumeGomez** [comment]
It depends on the kind of release: minor, medium or major. Since next one will be a major, the next version will be 0.7.0 and not 0.6.2.

**Comment by GuillaumeGomez** [comment]
And we have the master branch which is supposed to be at the same version as the crate one normally (it doesn't include sub-releases though).

**Comment by sdroege** [comment]
That's my point, the master branch should always be 0.X+1.0 compared to the version on crates.io as it will basically always contain API changes. If there's a 0.X.1 bugfix release later it will be from a branch anyway.

**Comment by GuillaumeGomez** [comment]
We can't know if we won't have a bug fix or a major release beforehand.

**Comment by sdroege** [comment]
That's what I'm saying :) master is always for a new major release, bugfix releases always come from a branch that only contains bugfixes. It's also very unlikely that master won't have any API changes at this point shortly after the release (until we reach 1.0 at least).

**Comment by GuillaumeGomez** [comment]
No, currently we've only made medium releases. :) I feel uneasy changing the version beforehand but I see that it can be misleading for users. Should maybe add a comment next to the version?

**Comment by kornelski** [comment]
I'm not sure why it has to be the next release. Being the same release is good too. 

The problem here is that it looks that **uncomitted** code has been released to crates.io. Could it bump version to whatever is necessary, commit, and then release to crates.io?

**Comment by GuillaumeGomez** [comment]
Oh! Found the branch: https://github.com/gtk-rs/glib/blob/0.6/Cargo.toml

**Comment by sdroege** [comment]
Yes what I mean is the following. Let's take the example of the next release, 0.7.0.

- You'd immediately create a `0.7` branch right after release that contains exactly what is in the 0.7.0 release

- You'd also create a `0.7.0` tag for that version.
- `master` would be updated to `0.8.0` and all development happens there and things will get broken as usual
- `0.8.0` would be later released from `master` like above for `0.7.0`
- `0.7.1` would be released from the `0.7` branch and would also immediately get a new `0.7.1` tag.
- `0.7` branch only gets manually selected bugfixes

That way everybody would see that `master` is the wild west and potentially incompatible with whatever is on crates.io currently, and there would be a `0.7` branch that would contain the latest bugfixes that are still compatible with crates.io. And whenever we want to do a bugfix release there wouldn't be anything complicated to do other than making sure the commits that are new in the `0.7` branch are all good to be released.

As all the releasing is done with a script this also shouldn't mean any additional manual work.

**Comment by kornelski** [comment]
Oh, I see. I didn't take release branches into account.

**Comment by sdroege** [comment]
All good here then? @GuillaumeGomez please remember for the next release :)
