### ISSUE TITLE
Context passed to Receiver::attach() is not released when removing its source

### ISSUE THREAD

**Issue by gdesmott** [gtk-rs/glib#454]
@sdroege : you told me the other day that the callback passed to `attach()` should be released when removing the source  but that doesn't seem to be the case according to this test case.

```rust
#[derive(Debug)]
struct Test(u32);

impl Drop for Test {
    fn drop(&mut self) {
        dbg!("dropped");
    }
}

pub fn main() {
    gtk::init().unwrap();

    let (_tx, rx) = glib::MainContext::channel(glib::PRIORITY_DEFAULT);

    let test = Test(1);
    let source = rx.attach(None, move |_u: u32| {
        dbg!(&test);
        glib::Continue(true)
    });

    glib::Source::remove(source).unwrap();

    gtk::main();
}
```

**Comment by sdroege** [comment]
That's bad :) Let's analyze that and transform it into an unit test then. Thanks for noticing!

**Comment by sdroege** [comment]
Your problem is that the sender (`_tx`) is still alive. The sender also has a reference to the underlying `GSource`, and the closure will only be dropped once the `GSource` is finalized. Which will happen once nothing has a reference to it anymore. In your case the reference owned by the main context is gone but the one from the sender not.

If you name it `_` instead of `_tx` it will also already be dropped. Assignments to `_` are dropped immediately, `_foo` is assigning to a variable that you can use but there won't be any warning about it not being used and once it goes out of scope it will be dropped.

**Comment by sdroege** [comment]
Let me know if this answers your question and if you think there's still something wrong here. There were actually tests for these already.

Note that the channel receiver is also automatically removed once the last sender is dropped (as there's no possible way for the closure to be called anymore after that).

**Comment by gdesmott** [comment]
Ah ok, I thought the context was dropped if either the source was removed or all the senders. Wouldn't that make sense from an API pov?

This is a simplified version of my problem as I was looking as a way to break reference cycles. I guess I'll have to drop the sender then.

**Comment by sdroege** [comment]
> Ah ok, I thought the context was dropped if either the source was removed or all the senders. Wouldn't that make sense from an API pov?

That would be ideal but I don't know how to implement that nicely. There's no `GSourceFunc` or anything that tells us when the `GSource` is removed (aka `g_source_destroy()`).

**Comment by sdroege** [comment]
Added another small test for a different variant: https://github.com/gtk-rs/glib/pull/455

When the receiver is removed from the context, all your senders will return errors when trying to send something. Maybe that can help in your case?

**Comment by sdroege** [comment]
> That would be ideal but I don't know how to implement that.

Actually I do. Needs some more indirection and splitting of state, but that's doable. I'll take a look at that in the next days, and as it seems like this weekend is not release weekend it would also be in the next release then :)

**Comment by GuillaumeGomez** [comment]
We still have cairo stuff to go through so not this week-end indeed.

**Comment by gdesmott** [comment]
Great! Let me know if you need testing, I'll be happy to give it a shot.

Btw, is there any reason we have to do `glib::Source::remove(source)`? Why not implement `remove()` on `SourceId` directly so we could use `source.remove()`?

**Comment by sdroege** [comment]
I've added an initial implementation here: https://github.com/sdroege/glib-rs/commit/b557cd1518a9252740e9c3f2d129c00df7b4482d

This does not work yet, the tests are failing and I need to add a few more tests too.
