### ISSUE TITLE
Move AppInfo and AppLaunchContext from gtk into this crate

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/glib#46]
The [AppInfo](https://github.com/rust-gnome/gtk/blob/f2353848504f62af08e6d658619733c0bda16588/src/widgets/app_info.rs) and [AppLaunchContext](https://github.com/rust-gnome/gtk/blob/f2353848504f62af08e6d658619733c0bda16588/src/widgets/app_launch_context.rs) implementations should be moved into this crate.
There is an empty [AppInfoExt trait](https://github.com/rust-gnome/glib/blob/master/src/app_info.rs#L19-23) that should receive the appropriate methods. `AppLaunchContext` could go into the same module.

**Comment by GuillaumeGomez** [comment]
I'll do it after the documencation part if it hasn't been done before.

**Comment by sdroege** [comment]
They're in gio and that's where they should be :)
