### ISSUE TITLE
Error Conversion

### ISSUE THREAD

**Issue by johollow** [gtk-rs/glib#474]
`gio`, contains `gio::Error`. `glib` has its own error types, and some functions (like `TextView::get_buffer`) return option types which the question mark operator will cast into `std::option::NoneError`. Often, all of these error types may be found inside the same function. It would be nice if there was a "mega-error" type that could be placed in the function return signature for all of these error types to convert to. Then, I could use the `?` operator without thinking too hard.

Perhaps this already exists. Am I missing an easy way to handle this problem? If not, it might be nice to implement a rusty error system.

**Comment by sdroege** [comment]
You could make your functions return `failure::Error` from the `failure` crate or `Box<dyn std::error::Error>`. The `?` operator would convert all the individual error types to those then.
