### ISSUE TITLE
GObject subclassing is verbose and boilerplate

### ISSUE THREAD

**Issue by ian-p-cooke** [gtk-rs/glib#492]
Is anyone working on cutting down the amount of code you have to write for a GObject subclass?  There's a lot more to it than the equivalent Python which in my case is just 
```Python
class Controller(GObject.GObject):
    input1 = GObject.Property(type=str)
    input2 = GObject.Property(type=str)
    output = GObject.Property(type=str)

    def __init__(self, adder):
        GObject.GObject.__init__(self)
```
A Rust GObject subclass is like 65 lines of mostly boilerplate.  I'm imagining some sort of fancy macro that would write most of that for you.

I was looking at https://raw.githubusercontent.com/gtk-rs/examples/master/src/bin/listbox_model.rs RowData for how to subclass GObject.  Is there maybe a better/less verbose way to do it?

**Comment by GuillaumeGomez** [comment]
We plan to do it (or at least greatly improve it), but for now it's still only the beginning.

**Comment by sdroege** [comment]
The basic implementation is going to stay (more or less) the same, but on top of that there's going to be a procedural macro that would take care of most of the boilerplate. You'd write some kind of C#/Rust-mix language inside the macro for defining the class.

**Comment by ian-p-cooke** [comment]
That sounds good.  Is there a tracking issue for the existing work?  Who's leading the effort?  If I can get some more time I might be able to help implement it or at least be a tester.

**Comment by sdroege** [comment]
https://gitlab.gnome.org/federico/gnome-class but it's not very active these days and also needs to be updated to the latest subclassing API that was merged into glib.

**Comment by ian-p-cooke** [comment]
thanks I'll check that out and catch up on the current state of things.
