### ISSUE TITLE
glib::Sender is not Clone when T is not Clone

### ISSUE THREAD

**Issue by Darksonn** [gtk-rs/glib#494]
The [`glib::Sender`][1] type implements `Clone` using a `#[derive(Clone)]`, which means the trait bound `T: Clone` is added. This means that channels that send non-cloneable messages cannot be cloned.

Please change it so cloning is done using an explicit `impl` block.

[1]: https://gtk-rs.org/docs/glib/struct.Sender.html

**Comment by sdroege** [comment]
Thanks, see https://github.com/gtk-rs/glib/pull/495
