### ISSUE TITLE
Iterate over the GList the Rust way

### ISSUE THREAD

**Issue by Boiethios** [gtk-rs/glib#503]
Is there a way to iterate over a `GList` with `for`?

I'm currently using [this kind of code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b50cbdc31dc9bf79531b5a1da37d79e8) (self-contained example):

```rust
#![feature(arbitrary_self_types)]

use std::marker::PhantomData;
use std::ptr::NonNull;

#[allow(non_camel_case_types)]
type gpointer = *mut std::ffi::c_void;

pub struct GList {
    pub data: gpointer,
    pub next: *mut GList,
    pub prev: *mut GList,
}

impl GList {
    pub fn iter<T>(self: *mut Self) -> GListIter<T> {
        GListIter {
            glist: NonNull::new(self),
            _marker: PhantomData,
        }
    }
}

pub struct GListIter<T> {
    glist: Option<NonNull<GList>>,
    _marker: PhantomData<T>,
}

impl<T> Iterator for GListIter<T> {
    type Item = *mut T;

    fn next(&mut self) -> Option<Self::Item> {
        self.glist.map(|current| {
            self.glist = NonNull::new(unsafe { (*current.as_ptr()).next });

            unsafe { (*current.as_ptr()).data as *mut T }
        })
    }
}
```

If a solution like that already exists, what is it?
Can I make a PR to add such a thing?

**Comment by sdroege** [comment]
There's currently no safe wrapper around `GList` and no safe bindings are actually returning a `GList`. Instead it will be converted to a `Vec` at the FFI layer.

As part of https://github.com/gtk-rs/glib/issues/230 I'd like to have proper bindings for `GList` though to not require the conversion to a `Vec` unless needed, and as part of that there would have to be code like the one you pasted above.

On it's own it seems not very useful though? Where/how are you using it?

**Comment by Boiethios** [comment]
That's mainly "cosmetic" (but is that bad?): I don't like to mix the "functional" code with the pointers stuff. That allows to write [some high-level code in my function](https://gitlab.com/Boiethios/goa-rs/blob/436eacd0735e240ab8078cee37282a64f4709240/src/client.rs#L30).

**Comment by Boiethios** [comment]
What do you mean by "no safe wrapper"? As long as the data is valid, this wrapper is safe. It is at least not less safe than the manual iteration.

**Comment by sdroege** [comment]
Where do you get a `GList` from over which you have to iterate?

**Comment by Boiethios** [comment]
https://developer.gnome.org/goa/stable/GoaClient.html#goa-client-get-accounts

**Comment by sdroege** [comment]
> What do you mean by "no safe wrapper"?

There is no safe wrapper around `glib_sys::GList` that allows to use it from safe code. The code you pasted above would be part of such a wrapper.

> https://developer.gnome.org/goa/stable/GoaClient.html#goa-client-get-accounts

If you generate bindings for that with gir it would give you a function that returns `Vec<goa::Client>`.

**Comment by Boiethios** [comment]
Sorry, I missed the "currently" in your sentence...

Thank you for pointing me in the direction of GIR. I didn't know that tool.

**Comment by sdroege** [comment]
Check https://gtk-rs.org/docs-src/tutorial/gir_tutorial for a tutorial using it.

Once you have bindings with that, you'll notice that you'll get a `Vec` here. If you don't want the copying, see the issue I linked further above.

**Comment by Boiethios** [comment]
Thanks again. I guess that this issue can be closed, since there is the one you linked that is more generic.
