### ISSUE TITLE
How do you connect signal in class_init ?

### ISSUE THREAD

**Issue by Ogromny** [gtk-rs/glib#509]
Hi,

I try to do this in Rust:
```c
static void x_application_class_init(XApplicationClass *class) {
    G_APPLICATION_CLASS(class)->activate = x_application_activate;
}
```

I tried to cast `klass: &mut Self::Class` in `gio_sys::GApplicationClass`, directly in `class_init`:
```rust
fn class_init(klass: &mut Self::Class) {
    *(klass as *mut GApplicationClass).activate = Some(...);
}
```
It doesn't work.

So I looked in the `crate`, and found `fn override_vfuncs(&mut self)`, but I don't understand how, I need to use this. I looked around in other public git, who used subclassing, but I still don't see how I need to use 

I also tried to upcast, but it doesn't work.

Thanks in advance.

PS: Sorry for my bad English... I'm :baguette_bread: French :baguette_bread: .

**Comment by sdroege** [comment]
On 2 August 2019 02:09:10 EEST, Ogromny <notifications@github.com> wrote:
>Hi,
>
>I try to do this in Rust:
>```c
>static void x_application_class_init(XApplicationClass *class) {
>    G_APPLICATION_CLASS(class)->activate = x_application_activate;
>}
>```
>
>I tried to cast `klass: &mut Self::Class` in
>`gio_sys::GApplicationClass`, directly in `class_init`:
>```rust
>    fn class_init(klass: &mut Self::Class) {
>        *(klass as *mut GApplicationClass).activate = Some(...);
>    }
>```
>It doesn't work.
>
>So I looked in the `crate`, and found `fn override_vfuncs(&mut self)`,
>but I don't understand how, I need to use this. I looked around in
>other public git, who used subclassing, but I still don't see how I
>need to use 

It's not a signal but a virtual method. Take a look at the unit test in gio/src/subclass/application.rs. That shows how to create a subclass of GApplication (we should create a better one though...).

You override the activate virtual method by implementing the activate function of the ApplicationImpl trait.

Please ask if something is not clear from that example so we can consider all that when creating a proper example for this. Thanks!


-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ogromny** [comment]
Thanks,

It's works now ^^. 

But I have a question, how should I need to implement `IsSubclassable` ?
```rust
use glib::subclass::object::ObjectImpl;
use glib::subclass::simple::*;
use glib::subclass::types::ObjectSubclass;

pub struct LupusBBox;

impl ObjectSubclass for LupusBBox {
    const NAME: &'static str = "LupusBBox";

    type ParentType = gtk::Box;
    type Instance = InstanceStruct<Self>;
    type Class = ClassStruct<Self>;

    glib_object_subclass!();

    fn new() -> Self {
        Self {}
    }
}

impl ObjectImpl for LupusBBox {
    glib_object_impl!();
}
```

**Comment by sdroege** [comment]
On 2 August 2019 15:06:22 EEST, Ogromny <notifications@github.com> wrote:
>Thanks,
>
>It's works now ^^. 
>
>But I have a question, how should I need to implement `IsSubclassable`
>?

You don't implement that but types that currently support subclassing from the bindings do.

In case of glib/gio/gtk that's only GObject, GApplication and GtkApplication right now. And basically all relevant types from GStreamer.

The same as for those has to be done for any other type that should be subclassable from Rust. Take a look in the src/subclass directories to see what is needed. We would be happy to review any PRs that add support for new types as needed.

>```rust
>
>    type ParentType = gtk::Box;
>```

gtk::Box is not supported yet but that should be a relatively easy one if you don't need to override also virtual methods from gtk::Widget.

I believe @alatiera shortly looked into that some months ago, but just go ahead with adding subclassing support for it. This PR should be good guidance for what has to be done:  https://github.com/gtk-rs/gtk/pull/814

If you don't want to work on that or don't have the time, please create an issue against gtk-rs/gtk for this. There will be a short hackfest for gtk-rs later this month together with GUADEC and around November a bigger one. Someone might want to take it up there then.

Out of curiosity, do you only need a subclass here to store your data or also for overriding behaviour?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdroege** [comment]
@Ogromny Any updates here from your side? :)
