### ISSUE TITLE
Impossible to distinguish Value::get::<glib::Object>() returning None because type mismatch or no value contained

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#510]
We should probably change the signature so that it returns a `Result`, and in case of nullable types (like objects) the success case of the `Result` would be an `Option`. The error case of the `Result` would happen on type mismatches.

Opinions?

**Comment by fengalin** [comment]
I agree!

**Comment by sdroege** [comment]
@GuillaumeGomez @EPashkin

**Comment by GuillaumeGomez** [comment]
I agree as well.

**Comment by EPashkin** [comment]
I also agree

**Comment by sdroege** [comment]
Ok, so now we only need to implement it then :)

**Comment by fengalin** [comment]
> Ok, so now we only need to implement it then :)

I can do that!
