### ISSUE TITLE
Make glib::value::GetError fields publics

### ISSUE THREAD

**Issue by fengalin** [gtk-rs/glib#515]
... so that we can read them outside of the module and we can build an error for use in `assert_eq!` expressions.

**Comment by sdroege** [comment]
Or a constructor? Either way seems fine to me

**Comment by fengalin** [comment]
Yeah, I'm not sure yet. We don't want users to change the fields values, but OTOH they might want to read the fields.

**Comment by fengalin** [comment]
Of course adding a constructor is useful, there's no question about this. One argument in favour of setting the fields as public is that when we declare an `Error` based on an `enum`, the variants fields are public.
