### ISSUE TITLE
Accessing raw GMainContext pointer

### ISSUE THREAD

**Issue by jnqnfe** [gtk-rs/glib#516]
Hi, I need to access the raw `GMainContext` pointer from a `MainContext` object. How do I do this?

I am the author of the PulseAudio rust bindings. PA has a glib-mainloop component system library which is one of the libs I provide a binding for.

A long standing todo item has been to link up the `GMainContext` opaque type I define to an actual glib oriented sys/binding crate. A new github issue from a user wanting to make use of PA+glib has prompted me to discover the existence of your `glib-sys` and `glib` crates and I have now tied them to `glib-sys::GMainContext`.

The problem though is that users will want to make use of `glib` and thus `Glib::MainContext`, but the PA `pa_glib_mainloop_new` C API function requires `*mut GMainContext`.

So, how can I access the raw pointer from `glib`? I've looked through the API docs and spent a little time last night in particular looking at the `translate` mod, but i was not immediately obvious if it was even possible to achieve through all of your abstractions. Perhaps I was right on the cusp of getting there, but I gave up and came here. Could you please point me in the right direction :)

I have noticed a little discussion here in #126, so I'll see if that gets me anywhere, but it would be great to have a direct example. Thanks :)

**Comment by EPashkin** [comment]
This is not enough?
```
//in ffi
    pub fn g_main_context_acquire(context: *mut GMainContext) -> gboolean;
//in main crate
    pub fn acquire(&self) -> bool {
        unsafe { from_glib(glib_sys::g_main_context_acquire(self.to_glib_none().0)) }
    }
```
https://github.com/gtk-rs/sys/blob/master/glib-sys/src/lib.rs#L3427
https://github.com/gtk-rs/glib/blob/master/src/auto/main_context.rs#L24-L26

**Comment by sdroege** [comment]
That's exactly what is needed here. `glib::translate::ToGlibPtr::to_glib_none()`.

**Comment by jnqnfe** [comment]
that works, thanks :)

I just failed in following various types and impls in the docs to connect the dots from things in `translate` to `MainContext`, nor could I follow the introduction in the `translate` page as it would relate to this type. I'll maybe take another look later to re-evaluate for myself how I failed to join those dots.

@EPashkin, ah yes, perhaps looking at the `MainContext` methods would have been a good strategy
