### ISSUE TITLE
Default behavior of the clone macro

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/glib#532]
I just realized something: by default, we still clone the content, not using the downgrade/upgrade mechanisms. From my point of view, we should do the opposite: downgrading/upgrading by default or cloning by specifying `@clone`.

cc @sdroege @EPashkin @antoyo

**Comment by sdroege** [comment]
I don't know, both are equally valid depending on the context. I would've prefixed things with `@weak` and `@strong` but I thought @antoyo had a reason to not do that :)

**Comment by antoyo** [comment]
I was having issues with writing the macro, but maybe it's fixed now and both way could have prefixes.

**Comment by GuillaumeGomez** [comment]
Let's go for prefixing everything then!
