### ISSUE TITLE
panic as clone return value?

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/glib#533]
In some cases, if the upgrading fails, we'd like to panic. For now it looks like this:

```rust
let listbox = gtk::ListBox::new();
listbox.bind_model(Some(&model),
    clone!(@weak window => @default-return panic!("failed to upgrade"), move |item| {
        // blablabla
    }));
```

What about adding another macro to handle such case? Like `clone_or_panic!` or something along the line?

**Comment by sdroege** [comment]
We could add a special variant to the macro for that. `clone!(@weak foo => @default-panic, move |bar| {...})`
