### ISSUE TITLE
Consider make path_to_c and os_str_to_c public

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/glib#546]
https://github.com/gtk-rs/glib/blob/master/src/translate.rs#L422-L486

cc @GuillaumeGomez, @sdroege

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by EPashkin** [comment]
Maybe this actually unneeded.
In case https://github.com/gtk-rs/cairo/pull/294 it will be not usable as it can unneeded non-optional dependence (https://github.com/gtk-rs/cairo/pull/294#issuecomment-561648241),
and if glib is used, user can just get `Option<Stash<xx,GString>>` with `to_glib_none`

**Comment by GuillaumeGomez** [comment]
Indeed, what I had in mind was more about letting users having access to it. But it'd be pretty useless in itself...

**Comment by sdroege** [comment]
Users already have access to it via `FromGlibPtr` on `Path`/etc :)
