### ISSUE TITLE
glib-macros: add derive for flags

### ISSUE THREAD

**Issue by gdesmott** [gtk-rs/glib#575]
Would be nice to have something similar to the `GEnum` derive macro for flags.

From https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/merge_requests/244#note_382747 :
> https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/blob/104458071a5d3a55e70c20be7ee6e6f492925ca6/gst/playback/gstplay-enum.c#L48-87 for the type registration (that's the same apart from the called function and the type). https://github.com/gtk-rs/gtk/blob/cbefe929a665260dd7ea93f9ecf1beeb7f304f3e/src/auto/flags.rs#L15-L62 for an example in Rust bindings how it should look like.
Basically we somehow need to wrap around the bitflags! macro here, or maybe do the derive inside the macro and assume it's inside a bitflags! context and otherwise we'll get compile errors.

**Comment by gdesmott** [comment]
Another good candidate for a derive macro would be boxer types: https://gtk-rs.org/docs/glib/subclass/index.html#example-for-registering-a-boxed-type-for-a-rust-struct

**Comment by gdesmott** [comment]
@sdroege : Looks like implementing a macro for flags is harder than expected.

I first tried with a derive macro as I did for `GEnum`:

```rust
    bitflags! {
        #[derive(GFlags)]
        #[gflags(type_name = "MyFlags")]
        struct MyFlags: u32 {
            const A = 0b00000001;
            const B = 0b00000010;
            const AB = Self::A.bits | Self::B.bits;
        }
    }
```

Problem here, the proc-macro is called **after** the `bitflags!` one has been expanded, so it no longer has access to the original code.

Then I tried implementing a superset of `bitflags!`:

```rust
    gflags! {
        #[gflags(type_name = "MyFlags")]
        struct MyFlags: u32 {
            #[gflags(name = "Flag A", nick = "A")]
            const A = 0b00000001;
            #[gflags(name = "Flag B", nick = "B")]
            const B = 0b00000010;
            #[gflags(name = "Flag A and B", nick = "A-B")]
            const AB = Self::A.bits | Self::B.bits;
        }
    }
```

That's almost good expect a couple of things I'm not sure how to do with such macro. See my two FIXME in [this test commit](https://github.com/gdesmott/glib/commit/0430aa9bac71a8a6af7603b2fd6aa6f6f1e15199#diff-4ca0d751189434e8a439006abfc18d3fR139).

Any smart idea?

**Comment by sdroege** [comment]
Or you could have the derive macro work on the expanded code from the `bitflags` macro, that's not going to change in shape because that would be a breaking change. Does that make anything simpler?

**Comment by sdroege** [comment]
@gdesmott Did you have any new ideas for this one?

**Comment by gdesmott** [comment]
No, still have to investigate if operating on the generated code is an option or not. Didn't had time to look at it yet.

**Comment by gdesmott** [comment]
@sdroege : so the problem is I'd have to do something like this in order to allow users define custom name and nick:

```rust
    bitflags! {
        #[derive(GFlags)]
        #[gflags(type_name = "MyFlags")]
        struct MyFlags: u32 {
            #[gflags(name = "Flag A", nick = "nick-a")]
            const A = 0b00000001;
            const B = 0b00000010;
            const AB = Self::A.bits | Self::B.bits;
        }
    }
```

But `#[gflags(name = "Flag A", nick = "nick-a")]` can't be handled by `bitflags!`  so I end up with an error: `error: cannot find attribute `gflags` in this scope`

Ideally `bitflags` should handle unknown attributes somehow. But where would it copied it in the generated code? The initial `struct` is converted to:

```rust
    struct MyFlags {
        bits: u32,
    }
```

so there is no longer room for the different flags values. :(

I suppose that leaves us with the only option to have a proc-macro generating the GLib boilerplate **and** the `bitflags!` struct but I'm not sure if that's actually possible.

**Comment by sdroege** [comment]
If you put the derive attribute on the `bitflags!` macro, what is the code you get passed into the macro? Before `bitflags!` expansion?

So yes I think we need a derive macro that expands into the trait impls we need plus some code with the `bitflags!`. I don't think that's a problem? You can use macros from inside macros.
