### ISSUE TITLE
Using g-source-set-funcs

### ISSUE THREAD

**Issue by windelbouwman** [gtk-rs/glib#584]
Is creation of a custom event in the event loop possible?

Looking at the gtk docs, it seems possible to create a custom event type:

https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-source-set-funcs

How would this work in rust? Does this work?

**Comment by sdroege** [comment]
What exactly is your use-case, what do you want to do?

All those C functions can be called from unsafe Rust via the `glib-sys` crate if needed. If you want to implement a custom `GSource` then that would currently be the way to go.

Alternatively you can use the futures integration of the main context. Each futures task that is spawned on the main context is actually a `GSource`.

**Comment by windelbouwman** [comment]
My use case is this:

I have a background thread which will generate data, and I want to put this on a queue. In the main event loop I want to block until this queue contains data, by means of a sort of select system call, or in GLib, I assume this is the GSource thing. Then, in the GUI I want to process both GUI events, such as mouse and keyboard, as well as events such as there is data from a background thread.

**Comment by sdroege** [comment]
For that you have a couple of options then:
- [glib::MainContext::channel()](https://gtk-rs.org/docs/glib/struct.MainContext.html#method.channel), which gives you an mpsc channel for passing something from another thread to the main loop, and having the main loop wait asynchronously on things to appear in the channel
- Use the futures support of the main context in any way that makes sense to you. You could use the futures channels (which basically gives you the same behaviour as the first option), or any other kind of future that can run on any futures executor, e.g. (probably does not compile as-is, but you get the idea)

```rust
let (sender, receiver) = futures_channel::mpsc::channel();
main_context.spawn_local(async move {
    while let Some(item) = receiver.next().await {
        do_something(item);
    }
});
```

The main context channel is a custom `GSource` if you're curious about the implementation, but we currently don't have safe API for implementing a new `GSource` completely from scratch, only the unsafe C API.

If you're interested in adding safe API for defining new `GSource`s, the main context channel implementation is probably a good starting point.

**Comment by sdroege** [comment]
Let me know if you have any questions about using those things or their implementation, or if that doesn't solve your problem at all yet :)

**Comment by windelbouwman** [comment]
Thanks a lot! I'm new to gtk, so not sure how to do this. I do not want to implement my own GSource if this is not required. Looks like there are enough options to do what I want, I'll give it a shot.

Is this use case documented anywhere?

**Comment by sdroege** [comment]
Not sure, it seems like a standard use-case. You do things in some thread and want to get the results back to the UI thread :)

There's a cairo/multithreading example inside the gtk-rs/examples repository that uses the main context channel. Apart from that there's not much documentation. What kind of documentation would you like to see and where? Then we can work on adding it :)

Without that documentation, do you have any questions, anything that needs clarification?

**Comment by windelbouwman** [comment]
I'm creating a plotting tool which receives data in a thread. Maybe an example with a thread reading data from serial port and updating a label would be a cool example?

**Comment by windelbouwman** [comment]
For reference, my implementation of exactly your idea is here: https://github.com/windelbouwman/lognplot/commit/3216baa9b1a20646524e7a863dd6f4830492161e

**Comment by sdroege** [comment]
> Maybe an example with a thread reading data from serial port and updating a label would be a cool example?

That's almost what https://github.com/gtk-rs/examples/blob/master/src/bin/cairo_threads.rs does, just without the serial port :)

**Comment by windelbouwman** [comment]
Agreed, but is there an example with the async/await future crate thing? A.k.a. the second option you suggested? This works really cool!

**Comment by sdroege** [comment]
Yeah that's much more flexible, I just can't think of a non-contrived example for this that is not huge and a complex application. Can you?

**Comment by windelbouwman** [comment]
Yes, see here: https://github.com/gtk-rs/examples/pull/289

**Comment by sdroege** [comment]
Ok :) let's close this one here then. Thanks!
