### ISSUE TITLE
confusing error message from clone!

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/glib#597]
I have tried to use the clone! macro with two use cases and I'm getting a confusing error message 

test case 1 
```
clone!(@strong row_sender => async move {
                    google_font.download().await.and_then(|()| {
                        send!(row_sender, RowAction::Installed);
                        Ok(())
                    });
                });
```

test case 2 
```
       let on_entry_changed = clone!(@weak self.fg_entry, self.bg_entry => move |_entry: &gtk::Entry| {
            let fg_colour = fg_entry.get_text();
            let bg_colour = bg_entry.get_text();

            state.borrow_mut().set_bg_colour(Some(&bg_colour));
            state.borrow_mut().set_fg_colour(Some(&fg_colour));

            send!(sender, Action::ColorChanged);
        });
```

In both cases I'm getting `Variables need to be valid identifiers, e.g. field accesses are not allowed as is, you must rename it!` which is a bit confusing

**Comment by sdroege** [comment]
The second one seems to tell you exactly what you did wrong there :) You need to rename the fields.

The first should work as is in that regard, but you have to provide a closure and not an async block. So the error message could be improved a bit there.

**Comment by GuillaumeGomez** [comment]
And for the first, I think the macro is failing to detect the missing "|whatever|" block.

**Comment by sdroege** [comment]
@GuillaumeGomez Is this fixed now with the latest change?

**Comment by GuillaumeGomez** [comment]
Checking.

**Comment by GuillaumeGomez** [comment]
The first test case now says "no rules expected the token \`async\`". The second says what it should. I'm adding a test case for the first just in case.
