### ISSUE TITLE
Cannot use gobject_sys::GCallback to pass function with arguments

### ISSUE THREAD

**Issue by brackleian** [gtk-rs/glib#598]
The type GCallback is defined as `Option<unsafe extern "C" fn()>`, however, many (?most) callback functions will require at least one argument. Example: gobject_sys::g_signal_connect_data() is defined as:
`pub unsafe extern "C" fn g_signal_connect_data(`
`    instance: *mut GObject, `
`    detailed_signal: *const c_char, `
`    c_handler: GCallback, `
`    data: gpointer, `
`    destroy_data: GClosureNotify, `
`    connect_flags: GConnectFlags `
`) -> c_ulong`
but the function passed as the `c_handler` parameter will typically require to be a function taking an argument, which will be passed the value of the `data` parameter.

**Comment by EPashkin** [comment]
This sample won't helps? https://github.com/gtk-rs/gtk/blob/master/src/text_buffer.rs#L25

**Comment by sdroege** [comment]
The type of `GCallback` is also like that on the C side. You're expected to cast whatever more specific callback type you have to `GCallback`, like in C.

Note also that there are safe bindings for `g_signal_connect*`: https://gtk-rs.org/docs/glib/object/trait.ObjectExt.html#tymethod.connect

**Comment by brackleian** [comment]
Hi Sebastian,

On Thu, 20 Feb 2020 00:38:08 -0800
Sebastian Dröge <notifications@github.com> wrote:

> The type of `GCallback` is also like that on the C side. You're expected to cast whatever more specific callback type you have to `GCallback`, like in C.

Apologies if this is a dumb newb question, my Rust experience is still low.  How exactly do you cast, for example:
	extern "C" fn(*mut gobject_sys::GObject)
to
	extern "C" fn()
which is required for gobject_sys::GCallback ?

Thanks,
Austin.

**Comment by sdroege** [comment]
See the example that @EPashkin linked, `connect_raw()` takes a `GCallback` as parameter.

**Comment by brackleian** [comment]
Aahh, lightbulb comes on at last! I was aware of `transmute` but (long time since I read the docs...) assumed it applied only to data objects, not functions. Many thanks to all for kindly pointing me in the right direction and not screaming RTFM! at me.   :)
