### ISSUE TITLE
Change from_glib_borrow() to return a wrapper struct

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#599]
The idea would be to get rid of the additional bool that is inside all our wrapper structs. It's a waste of space and generally wastes one additional pointer (due to padding) per object :)

Instead that special case would be completely removed from the wrapper structs and moved into a new wrapper struct on top of it, i.e.

```rust
fn from_glib_borrow(ptr) -> glib::Borrowed<T>;

struct Borrowed<T>(T);

impl<T> Deref for Borrowed<T> { ... }
impl<T> AsRef for Borrowed<T> { ... }

impl<T> Drop for Borrowed<T> {
    fn drop(&mut self) {
        mem::forget(self.0);
    }
}
```

This would also make it much less likely that it would accidentally be passed to safe Rust code.

Opinions @EPashkin @GuillaumeGomez ?

**Comment by GuillaumeGomez** [comment]
I need to check the exact differences between the two. Will check tomorrow. We can talk about it directly tomorrow if you prefer too?

**Comment by EPashkin** [comment]
@sdroege I like this idea

**Comment by sdroege** [comment]
@GuillaumeGomez sure just let me know when you're available

**Comment by sdroege** [comment]
> <imperio> sounds good to me, thanks for the explanations!

So now it only has to be implemented and code be changed everywhere :)

**Comment by sdroege** [comment]
cairo needs to be manually updated to a similar approach
