### ISSUE TITLE
Lots of Error::description() deprecation warnings with 1.42

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#613]
We should either move to `thiserror` like in cairo for our errors, or at least just not implement that function.

**Comment by sdroege** [comment]
@GuillaumeGomez Any objections against using `thiserror`?

**Comment by GuillaumeGomez** [comment]
I'll complain but you can go forward with it.

**Comment by gdesmott** [comment]
Just build `glib` master with 1.42 and didn't get any warning. Do I have to use specific flags?

**Comment by GuillaumeGomez** [comment]
@gdesmott You're sure you didn't allow all warnings in your environment variables by any chance? Also, try `rustc --version` just to be sure. :)

**Comment by EPashkin** [comment]
Just glib or gtk/examples?

**Comment by gdesmott** [comment]
Just glib, don't have any warning building https://github.com/gtk-rs/examples either.

```
$ rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)
```

**Comment by EPashkin** [comment]
Then issue fixed without linking it in PRs. Ex. my cairo PR about this was before this issue.

**Comment by sdroege** [comment]
It's not fixed, see for example the two `Error` impls in `glib/src/error.rs`. We need to go through all `Error` impls in our crates.

**Comment by gdesmott** [comment]
ah, I get the warnings when running `cargo test`!

**Comment by gdesmott** [comment]
Not sure how we'd like to change the test with this change. I suppose hardcoding source code line numbers in tests isn't ideal.

```
---- subclass::object::test::test_set_properties stdout ----
thread 'subclass::object::test::test_set_properties' panicked at 'assertion failed: `(left == right)`
  left: `"Error \"property not found\" in \"glib::object\" at src/object.rs:1365"`,
 right: `"property not found"`', src/subclass/object.rs:605:9
```

**Comment by sdroege** [comment]
CC @fengalin who added this test

**Comment by sdroege** [comment]
The same will be needed in other repositories.

**Comment by fengalin** [comment]
I'll see what I can do, but I'd like to focus on completing https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/298

**Comment by sdroege** [comment]
@gdesmott actually was looking into that (`Error::description`) before you took over :)

**Comment by fengalin** [comment]
Ok :) Let's synchronize here if someone starts updating another repo for this.

**Comment by gdesmott** [comment]
Which repos need to be fixed as well? I don't have a full checkout so can't easily grep them.

**Comment by sdroege** [comment]
No others apparently. cairo and gstreamer are already done, the others don't have custom error implementations
