### ISSUE TITLE
Consider implementing ToValue in glib_object_wrapper!

### ISSUE THREAD

**Issue by thutchmoto** [gtk-rs/glib#631]
I'm working with difference rust wrappers/bindings for various glib-based libraries, such as libnice and gstreamer. It would be awesome if definitions emitted from glib_object_wrapper! also included the ToValue trait, so any such object can be injected into an object property as a Value (where appropriate of course). 

For example: in gstreamer, there are `nicesrc` and [`nicesink`](https://github.com/shadeslayer/libnice/blob/master/gst/gstnicesink.c) elements that expose a property named `agent`; this property is an object pointer to a libnice agent. 

I had to add a custom implementation of ToValue to NiceAgent. It wasn't that big of a deal, but I anticipate having to do something like this several more times. 

Maybe implementing ToValue isn't the right way; maybe there's a better way? If so I'd like a suggestion.

**Comment by sdroege** [comment]
`glib_object_wrapper!` already implements `SetValueOptional` (and `FromValue`, etc), which will give you `ToValue` (and other things) for free.

Why doesn't it work for you as-is? Can you give some example code that shows your problems?

> such as libnice and gstreamer

Note that GStreamer already has [bindings](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs)

**Comment by sdroege** [comment]
Also note that the macro you want to use is `glib_wrapper!`. `glib_object_wrapper!` is an internal macro called by it. And not sure if you saw the code generator [gir](https://github.com/gtk-rs/gir/), that might save you some time.

**Comment by thutchmoto** [comment]
Well, sorry to waste your time. I don't know how I possibly missed that. I guess this can be closed. 

Actually, I was using code from a repo that wasn't using the glib_wrapper! macro. So I had to implement ToValue myself. And it seems that that repo has very recently been updated and now uses the macro.

**Comment by sdroege** [comment]
No worries. Which repo is that and what bindings do you plan to work on exactly? libnice?

**Comment by thutchmoto** [comment]
Affirmative. [rust-libnice](https://github.com/Johni0702/rust-libnice)
