### ISSUE TITLE
No documentation on subclassing

### ISSUE THREAD

**Issue by john01dav** [gtk-rs/glib#642]
In one of my projects, I need to subclass a GObject class in order to implement some custom functionality with an existing widget (it isn't possible to do this without subclassing). Unfortunately, I can't find any documentation on how to do so (something about Impl traits, which don't seem to exist, and implementing `IsA` requires unsafe code, but I want safe subclassing). [The main documentation](https://gtk-rs.org/docs-src/tutorial/) doesn't mention it at all.

**Comment by sdroege** [comment]
There's some module-level documentation here: https://gtk-rs.org/docs/glib/subclass/index.html

There's also an example here: https://github.com/gtk-rs/examples/blob/master/src/bin/basic_subclass.rs

And various subclass implementations in the gio repository, and in GStreamer.

What GObject class do you want to inherit from?

**Comment by john01dav** [comment]
The first link seems to give a coherent view of how to make the subclass, but it relies on some traits that don't exist for [the class that I want to inherit from](https://gtk-rs.org/docs/sourceview/struct.CompletionProvider.html), as I'm trying to implement my own auto-completion algorithm for GtkSourceView. The second link also has a lot of extra stuff going on, and it isn't clear to me where that stuff is coming from (e.g. the glib_wrapper! macro is there, but has no comments explaining its purpose). Both links seem to require some traits that don't exist for the specific class in question, which is problematic because, as far as I can tell, subclassing this class is the only way to implement custom auto-completion (this subclassing seems like a lot of work outside of the problem that I'm trying to solve with my program, so if there's a simpler interface, I'd rather use that).

**Comment by sdroege** [comment]
> The first link seems to give a coherent view of how to make the subclass, but it relies on some traits that don't exist for [the class that I want to inherit from](https://gtk-rs.org/docs/sourceview/struct.CompletionProvider.html)

Yeah, sourceview has no subclassing support yet. That's maintained by @GuillaumeGomez so you'd have to check plans with him there.

Also `CompletionProvider` is an interface and not a base class, which has to be handled slightly different (`gio::InputStream` would be a good example from the gio crate for that stuff, and the `ReadInputStream` implementation of it inside gio).

You (or someone else) would have to add the required traits and subclassing bindings to the sourceview bindings for this to be possible. How that works is not very well documented yet unfortunately, but there are lots of examples in `gio`, gtk` and `gstreamer` at this point that could be used as a starting point.

> this subclassing seems like a lot of work outside of the problem that I'm trying to solve with my program, so if there's a simpler interface, I'd rather use that

I don't really know the sourceview API, but the only other way would seem to be via an existing implementation of that interface. E.g. `GtkSourceCompletionWords`.

**Comment by sdroege** [comment]
Also let me know if you want to work on adding the subclassing pieces for this specific interface to the sourceview bindings. Then I can give you links to good code examples for what has to be done there in this case.

**Comment by john01dav** [comment]
@sdroege Thanks for all your help. This seems like it's a sourceview binding issue, so I'm going to close this issue and open a new one there. I'm not opposed to doing that implementation myself, but I'm new to all of Rust, GTK, and these bindings, so I'm far from the most qualified person to do that (although I am not new to programming in general, and have done multiple substantial projects before with different tools). As such, I'm going to wait and see what Guillaume Gomez has to say before I attempt the implementation myself, as it may be something that they're willing to do.

**Comment by GuillaumeGomez** [comment]
No I don't intend to do it anytime soon. :)

**Comment by alatiera** [comment]
FYI, the sourceview repo in gtk-rs is referring to sourceview3 which isn't used in many places anymore so I don't think its worth spending any time on that. Most things have migrated already to sourceview4 and the bindings for that are hosted over here https://gitlab.gnome.org/World/Rust/sourceview4-rs/

**Comment by sdroege** [comment]
See also https://github.com/gtk-rs/sourceview/issues/130
