### ISSUE TITLE
unresolved name `gobject_ffi::g_value_set_schar

### ISSUE THREAD

**Issue by Annwenn** [gtk-rs/glib#68]
Hello,
I am trying to compile [rrun](https://github.com/buster/rrun) which uses this library.
When I run `cargo build`, cargo throws the following errors:

```
/home/uniaika/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.0.4/src/value.rs:69:18: 69:48 error: unresolved name `gobject_ffi::g_value_set_schar` [E0425]
/home/uniaika/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.0.4/src/value.rs:69         unsafe { gobject_ffi::g_value_set_schar(&mut self.inner, v_char) }
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/uniaika/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.0.4/src/value.rs:69:18: 69:48 help: run `rustc --explain E0425` to see a detailed explanation
/home/uniaika/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.0.4/src/value.rs:74:18: 74:48 error: unresolved name `gobject_ffi::g_value_get_schar` [E0425]
/home/uniaika/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.0.4/src/value.rs:74         unsafe { gobject_ffi::g_value_get_schar(&self.inner) }
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/uniaika/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.0.4/src/value.rs:74:18: 74:48 help: run `rustc --explain E0425` to see a detailed explanation
```

**Comment by gkoz** [comment]
It looks like your `glib` library is older than `2.32`. What's your distro and do you think you could upgrade?

We don't actually require 2.32 but we had to pick some minimum version and it's very difficult to do CI against obsolete versions.

**Comment by Annwenn** [comment]
I'm running Funtoo Linux, with glib v2.44.1  
Here's a screenshot:

![screenshot-2015-10-15-16-44-09_1366x768](https://cloud.githubusercontent.com/assets/8963482/10517237/344b28b0-735c-11e5-9cae-03e799f4f3c9.png)

**Comment by gkoz** [comment]
Interesting. Could you do
```
cargo clean
cargo build -v > build.log
```
and post the `build.log` somewhere?

I'd also like to see the output of
```
pkg-config --modversion glib-2.0
pkg-config --modversion gtk+-3.0
pkg-config --cflags --libs gtk+-3.0
```

**Comment by Annwenn** [comment]
Here are the pkg-config results:
![screenshot-2015-10-15-16-59-14_1366x768](https://cloud.githubusercontent.com/assets/8963482/10517700/3570920a-735e-11e5-8879-0699c509df05.png)

And the [build log](https://gist.github.com/Annwenn/f59ceeb4d6f71919ed5c)

**Comment by gkoz** [comment]
It appears cargo isn't running the build scripts. I don't see a single line like this:
```
/home/uniaika/repos/rustypo/rrun/target/debug/build/glib-sys-a1d4bd7a92710d34/build-script-build
```

Could be some broken `cargo` version or you might have a weird `.cargo/config` somewhere.

**Comment by Annwenn** [comment]
I use multirust, so I'm going to update to latest nightly.
(And I don't have a ~/.cargo/config)

**Comment by gkoz** [comment]
My last comment was incorrect anyway, I'm still looking at the log.

**Comment by Annwenn** [comment]
okay :')

**Comment by gkoz** [comment]
The build scripts are run but it's not clear why they don't generate any `--cfg` directives. What will this print after a failed build?
```
./target/debug/build/gobject-sys-ca96716312296c11/build-script-build
```

**Comment by Annwenn** [comment]
```
uniaika 17:44 (master ⚡ ) ~/repos/rustypo/rrun ❯❯ ./target/debug/build/gobject-sys-*/build-script-build
./target/debug/build/gobject-sys-ca96716312296c11/build-script-build: symbol lookup error: ./target/debug/build/gobject-sys-ca96716312296c11/build-script-build: undefined symbol: _ZN11collections4hash5table16round_up_to_next10_FILE_LINE20h50c8c1d83ed81998H4bE
```

**Comment by gkoz** [comment]
Apparently there's something wrong with your multirust installation. Running a binary shouldn't fail like this.

**Comment by gkoz** [comment]
Unless you switched the multirust override between building and running.

**Comment by Annwenn** [comment]
I just updated. Here's the last command ran again

```
uniaika 17:44 (master ⚡ ) ~/repos/rustypo/rrun ❯❯ ./target/debug/build/gobject-sys-ca96716312296c11/build-script-build
cargo:rustc-link-lib=gobject-2.0
cargo:rustc-link-search=native=/usr/lib64
cargo:rustc-link-lib=glib-2.0
cargo:rustc-cfg=gobject_2_32
cargo:rustc-cfg=gobject_2_34
cargo:rustc-cfg=gobject_2_36
cargo:rustc-cfg=gobject_2_38
cargo:rustc-cfg=gobject_2_42
cargo:rustc-cfg=gobject_2_44
cargo:cfg=gobject_2_32 gobject_2_34 gobject_2_36 gobject_2_38 gobject_2_42 gobject_2_44
```

**Comment by gkoz** [comment]
Okay if you can confirm that this build script does print
```
cargo:rustc-cfg=gobject_2_32
```
 and `cargo -build -v` doesn't show `--cfg gobject_2_32` passed to `rustc` in this line
```
Running `rustc /home/uniaika/.cargo/registry/src/github.com-1ecc6299db9ec823/gobject-sys-0.2.0/src/lib.rs --crate-name gobject_sys ...
```
there is a problem with cargo.

I can't reproduce this with neither of `cargo 0.6.0-nightly (7b630d4 2015-10-12)` or `cargo 0.4.0-nightly (553b363 2015-08-03) (built 2015-08-02)`

**Comment by Annwenn** [comment]
Here's said line:

```
     Running `rustc /home/uniaika/.cargo/registry/src/github.com-1ecc6299db9ec823/gobject-sys-0.2.0/src/lib.rs --crate-name gobject_sys --crate-type lib -g -C metadata=ca96716312296c11 -C extra-filename=-ca96716312296c11 --out-dir /home/uniaika/repos/rustypo/rrun/target/debug/deps --emit=dep-info,link -L dependency=/home/uniaika/repos/rustypo/rrun/target/debug/deps -L dependency=/home/uniaika/repos/rustypo/rrun/target/debug/deps --extern glib_sys=/home/uniaika/repos/rustypo/rrun/target/debug/deps/libglib_sys-a1d4bd7a92710d34.rlib --extern bitflags=/home/uniaika/repos/rustypo/rrun/target/debug/deps/libbitflags-ab4a647a363172d8.rlib --extern libc=/home/uniaika/repos/rustypo/rrun/target/debug/deps/liblibc-27ac2b23c7859a5a.rlib -Awarnings -L native=/usr/lib64 -l gobject-2.0 -l glib-2.0 -L native=/usr/lib64`
```

**Comment by gkoz** [comment]
Seems like a `cargo` issue then. :(

**Comment by gkoz** [comment]
The docs say it must pass the `--cfg` arguments returned by the build script: http://doc.crates.io/build-script.html#outputs-of-the-build-script

**Comment by Annwenn** [comment]
Too bad then :P I'll try building it on another machine then o/
Thanks again :)

**Comment by gkoz** [comment]
I don't think anyone else has been able to reproduce this.
