### ISSUE TITLE
Rename Variant constructors from new_XXX()

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/glib#680]
More consistent with other constructors would be e.g. `from_variant()` instead of `new_variant()`.

CC @zeenix

**Comment by zeenix** [comment]
> More consistent with other constructors would be e.g. `from_variant()` instead of `new_variant()`.

The `new_` constructors are named like the underlying C API for consistency. I think it's how it should be.

**Comment by sdroege** [comment]
> The `new_` constructors are named like the underlying C API for consistency. I think it's how it should be.

No, we decided for the last release to follow Rust conventions for that and that's also what `gir` does now :) Constructors with arguments become `from_xxx()`, `with_xxx()`, etc. without the `new_` prefix.

**Comment by zeenix** [comment]
Ah ok then.

**Comment by zeenix** [comment]
However, this is a different case I think cause `new_array` e.g doesn't create a variant from an array but more like create an array-type variant. `new_array` doesn't even take an array but rather a slice so it feels wrong for at least array. Similarly `new_variant` creates a variant-type variant, although it takes a `variant` as arg so `from_variant` wouldn't be so misleading. How about just `array` and `variant`?

**Comment by sdroege** [comment]
Yes that makes more sense in this context indeed

**Comment by zeenix** [comment]
> Yes that makes more sense in this context indeed

which one? Existing names or new ones I proposed?

**Comment by sdroege** [comment]
The new ones you proposed

**Comment by sdroege** [comment]
That also follows the Rust naming scheme
