### ISSUE TITLE
Add wrappers for GVariantIter

### ISSUE THREAD

**Issue by ids1024** [gtk-rs/glib#682]
This seems like it could be useful, with a call like `Variant::iter`.

Implementing this seems to run into an issue:

```rust
glib_wrapper! {
    pub struct VariantIter(Boxed<glib_sys::GVariantIter>);

    match fn {
        copy => |ptr| glib_sys::g_variant_iter_copy(ptr),
        free => |ptr| glib_sys::g_variant_iter_free(ptr),
    }
}
```

This fails to compile since `g_variant_iter_copy()` takes a `*mut`, not a `*const`. This is easily fixed with `ptr as *mut _`, but of course Rust considers that undefined behavior.

Not sure what the best solution is. Change the `glib_wrapper!` macro?

**Comment by sdroege** [comment]
Cast or use the mut_override function. it's not UB on pointers, only on references.
