### ISSUE TITLE
Assertion error on ObjectSubclass::get_instance() with zero sized type

### ISSUE THREAD

**Issue by ids1024** [gtk-rs/glib#701]
If a zero-sized type implements `ObjectSubclass`, calling `get_instance()` errors:

```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /home/ian/src/glib-rs/src/subclass/types.rs:300:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This assert is failing:

https://github.com/gtk-rs/glib/blob/0cc0a46c6da1cd7c853cef8f6851d80d4a0de202/src/subclass/types.rs#L300

Removing the assertion fixes it. I don't know if there's a good reason to have the assertion. If it's to verify the offset has been set, perhaps it should use a sentinel value other than 0.

I came across this just testing the API, and the struct I actually was going to use wasn't zero-sized. But there are probably some sane uses for a GObject with no data members (except those in a parent type).

**Comment by sdroege** [comment]
Yes that assertion shouldn't be there at all :) Previously (before https://github.com/gtk-rs/glib/commit/bbe787c1aaf6f450b33bd4102acbfd7cbd525bb3) it was not possible to have a ZST for it. It would always be an `Option<_>` instead, but when doing that change I apparently forgot this assertion.

Do you want to submit a PR for this?

**Comment by sdroege** [comment]
And if so, please also extend the test here with a call to `get_instance()`:

https://github.com/gtk-rs/glib/blob/0cc0a46c6da1cd7c853cef8f6851d80d4a0de202/src/subclass/object.rs#L332

**Comment by sdroege** [comment]
This is also fixed on crates.io in 0.10.3 now. Thanks!
