### ISSUE TITLE
Using glib_wrapper! with Shared twice in the same module fails

### ISSUE THREAD

**Issue by ids1024** [gtk-rs/glib#714]
Just noticed this looking at the code for `glib_shared_wrapper!`. The macro defines a `pub enum MemoryManager {}`, so if it's called twice in the same module, it will error about that type being defined twice.

A failing test case, for completeness:

```rust
glib_wrapper! {
    pub struct Shared1(Shared<()>);
    match fn {
        ref => |x| x,
        unref => |x| (),
    }
}

glib_wrapper! {
    pub struct Shared2(Shared<()>);
    match fn {
        ref => |x| x,
        unref => |x| (),
    }
}
```

**Comment by sdroege** [comment]
Yeah I worked around that in `glib/src/param_specs.rs` with separate modules but ideally that should be fixed :)

**Comment by sdroege** [comment]
I wonder if using `PhantomData<T>` where `T` is an uninhabited type is actually undefined behaviour, strictly speaking

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/glib/pull/715

**Comment by ids1024** [comment]
> I wonder if using PhantomData<T> where T is an uninhabited type is actually undefined behaviour, strictly speaking

I think if it were it would be considered a compiler bug, since there's nothing unsafe about constructing a `PhantomData` or defining an empty type.
