### ISSUE TITLE
setting glib value to f64

### ISSUE THREAD

**Issue by dallyshalla** [gtk-rs/glib#72]
https://github.com/gtk-rs/glib/blob/d8d5df3f9455d885f85740a5b08aa507e2dacb99/src/value.rs

I see that we can do set_long

can we do set_double, it is a private function, is that for a reason? I am not able to otherwise set glib value to a double; any ideas here?

**Comment by GuillaumeGomez** [comment]
We limited glib/Value struct because of the global glib instability at this time. I don't see any current issue that would maintains this state. Maybe do you see one (or more ?) @gkoz ?

**Comment by gkoz** [comment]
That some of the functions are public and others are not seems like an oversight. These `Value` bindings appear to be problematic though. They should be checking the type and returning `Option`.

**Comment by dallyshalla** [comment]
I also worked around for the GUI by setting all values to string and diplaying them from there;

I see what you mean that they should check type then return Option;

**Comment by gkoz** [comment]
I'm going to close this in favor of the more general #73.
