### ISSUE TITLE
FileError variant names are confusing

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/glib#98]
The [`FileError` enum](https://github.com/gtk-rs/glib/blob/master/src/file_error.rs) variant names are cryptic and confusing. We should consider changing them to platform neutral understandable names similarly to `std::io::ErrorKind`. See also [errno to ErrorKind](https://github.com/rust-lang/rust/blob/0486e12ad0661adcfdbd926dea17d7edfda419c1/src/libstd/sys/unix/mod.rs#L89-L101) conversion.

**Comment by sdroege** [comment]
These are autogenerated now and consistent with how other error enums look like
